### ISSUE TITLE
Hide the Try Gutenberg callout

### ISSUE THREAD

**Issue by pento** [WordPress/classic-editor#1]
We should hide the Try Gutenberg callout all the time, as it's kind of confusing to still be offering Gutenberg when folks have opted out.

It currently isn't being hidden if you have the Classic Editor plugin installed, but Gutenberg isn't.

The `remove_action( 'try_gutenberg_panel', 'wp_try_gutenberg_panel' );` call needs to be moved to the top of the function.

**Comment by danielbachhuber** [comment]
Looks like this was fixed in 3cf2f364b504c962705ba2b25ae262f73646af5a ?

**Comment by danielbachhuber** [comment]
Sorry, I meant RC1, not trunk.

**Comment by pento** [comment]
Yeah, 0.4 fixed it, I just hadn't closed this ticket. 🙂
