### ISSUE TITLE
Preserve Privacy Policy help notice on `edit_form_after_title` hook.

### ISSUE THREAD

**Issue by desrosj** [WordPress/classic-editor#10]
When the classic editor is installed, the current location of the Privacy Policy help notice (`edit_form_after_title` action hook) should be preserved.

This hook is no longer supported in the new editor, and [Trac-45057](https://core.trac.wordpress.org/ticket/45057) will switch the action hook to `admin_notices` in order to support the new editor. The Classic Editor plugin should maintain the `> 5.0` location.

**Comment by azaozz** [comment]
Thinking this should probably be in core where we add the notice. But lets do it for now from Classic Editor.

**Comment by azaozz** [comment]
Done in https://github.com/WordPress/classic-editor/commit/7076276361f026262a8884525df8a2153bbdb88b.
