### ISSUE TITLE
Classic Editor removing line breaks

### ISSUE THREAD

**Issue by heilincoo** [WordPress/classic-editor#103]
I am using the Classic Editor by default.  I select Edit Page, a page which was previously created using line breaks.  As soon as the page opens, the line breaks are gone.  All the lines are contained in a single paragraph.  How can I correct this?  If this is a bug, is there a temporary work-around which doesn't involve writing php code?  thanks,
[LineBreakProblem.txt](https://github.com/WordPress/classic-editor/files/3420025/LineBreakProblem.txt)

**Comment by ermite-athee** [comment]
**_??????????????????? in french ?_**

**Comment by heilincoo** [comment]
This problem has been fixed.
