### ISSUE TITLE
Changes to the readme.txt

### ISSUE THREAD

**Issue by roelti** [WordPress/classic-editor#105]
I would suggest to change the readme.txt to a more readable readme.md (with Markdown formatting) so there is more markup in the text. This makes the readme a bit more readable (headings are bigger, list items are displayed as such).

**Comment by roelti** [comment]
I made a pull request for this :)

**Comment by azaozz** [comment]
`readme.txt` is needed for the WordPress plugin repository, and user feedback and questions are handled there. This repo is only for development, not sure it needs a separate readme.md.
