### ISSUE TITLE
My WordPress/classic editor is Acting Up and I can't Edit Posts at all

### ISSUE THREAD

**Issue by lannit-g** [WordPress/classic-editor#108]
Just checking...  My WordPress/classic editor suddenly appeared in a much smaller size format yesterday. The text view was visible for posts and pages but not the visual view.  Today the classic editor is back to its original appearance, but there is no content available in either the visual or text views.  Checking the actual posts and pages on the website westernmasscoaches.com, however, reveals that the content is still tthere.  I have PHP version 7.2.7 -- could there be a compatibility problem with this PHP version?  Do you have other ideas about why the editor is acting up?

**Comment by hilfans** [comment]
i'm also have the same problem

**Comment by lannit-g** [comment]
My problem was mostly solved by white listing my IP address with the Sucuri security firewall I use (other security systems like Lifelock also put a firewall between users, even administrators, and the actual web page). I'm still having problems with some editing functions, such as moving an image and a few others and will put in a ticket at Sucuri to ask about these problems and will report here what I find out.

**Comment by azaozz** [comment]
Glad you were able to find the problem.

First step of troubleshooting in cases like this one should always be to look for JS errors in the browser tools.
