### ISSUE TITLE
Distraction-free writing mode problems

### ISSUE THREAD

**Issue by galbaras** [WordPress/classic-editor#109]
1. When I use the keyboard shortcut "Shift+Alt+W", as suggested by the distraction-free writing mode button popup, nothing happens.

2. When I click on the "distraction-free writing mode" button, the only thing that happens is that the admin menu sidebar and the post details sidebar disappear. The editor does not expand, and the browser window doesn't go full screen.

3. While in distraction-free writing mode, if I move the mouse outside the editor area, both sidebars return to clutter the view, while the button remains "pressed". To resume distraction-free writing mode, I now have to click the button twice.

4. When the browser window width is <= 850px, the admin sidebar disappears again when the mouse is returned to the editor, which is great. However, the post details sidebar disappears and does not return.

The above is all for Chrome 79 on Windows 10.

**Comment by azaozz** [comment]
> The editor does not expand, and the browser window doesn't go full screen.

This has never been part of the (default) distraction-free mode.

> While in distraction-free writing mode, if I move the mouse outside the editor area, both sidebars return to clutter the view, while the button remains "pressed".

This was added few releases (coupe of years?) ago. It temporarily shows the rest of the UI on mouse movement, and hides it few seconds later if the mouse is not moved again.

**Comment by azaozz** [comment]
This is functionality in WP, not added by this plugin.

**Comment by galbaras** [comment]
WordPress core no longer accommodates the classic editor, and the plugin supposedly restores that editor functionality. Therefore, it seems to me that it should restore everything that was possible in the editing experience, including distraction free mode.
