### ISSUE TITLE
Problem with ol / ul in Backoffice

### ISSUE THREAD

**Issue by sebastienserre** [WordPress/classic-editor#114]
Hello,

Under WordPress 5.4 with TwentyTwenty and Classic Editor 1.5 from wp.org.

I add  `<ol>` with the buttons and in text mode it's `<ul>` rendered.

![ol in visual](https://i.imgur.com/p5CAOz8.png)
![ol in test](https://i.imgur.com/LXtAlvZ.png)

In front there's no problem.

**Comment by sabernhardt** [comment]
It's a Twenty Twenty issue, now added on a Trac ticket:
https://core.trac.wordpress.org/ticket/50454

**Comment by azaozz** [comment]
Thanks @sabernhardt, closing it here.
