### ISSUE TITLE
Make Classic_Editor::is_classic() a public method

### ISSUE THREAD

**Issue by r-a-y** [WordPress/classic-editor#116]
Sometimes it is useful for plugins to determine whether a post is using the Classic Editor or not.

Is there any reason why `Classic_Editor::is_classic()` is a private method and not public?
https://github.com/WordPress/classic-editor/blob/b2a28d37cc61d953d21b8fd3809882f0e43d90dc/classic-editor.php#L280

**Comment by azaozz** [comment]
> Is there any reason why Classic_Editor::is_classic() is a private method and not public?

The main reason is that it won't work properly unless a post is being loaded for editing (it looks at `$_GET` and expects few things to be set there).

Thinking if it is public, other plugins may expect it to always work, but that will bring many "edge cases" where it fails.

Going to close this for now. Please feel free to reopen perhaps with a way to make `is_classic()` work more consistently so it can be public.
