### ISSUE TITLE
Can't find post revisions

### ISSUE THREAD

**Issue by galbaras** [WordPress/classic-editor#117]
I'm trying to find the link to listing post revisions, but it's gone. I thought this was a "screen option", but it's not there either.

Is this a deliberate change in the Classic Editor plugin? If not, it may be a bug.

How do I list the revisions of a post with the plugin installed?

**Comment by azaozz** [comment]
The Classic Editor plugin doesn't change anything on the old Edit Post screen. Could it be that there are currently no revisions? (If I remember right the revisions postbox is shown only when there are revisions).

Closing as this seems unrelated.
