### ISSUE TITLE
Why this Option not Enabled i have successfully installed plugin 

### ISSUE THREAD

**Issue by DhavalGevariya** [WordPress/classic-editor#118]
![Screenshot 2020-05-21 at 8 45 08 PM](https://user-images.githubusercontent.com/30233160/82574260-72221700-9ba4-11ea-83ec-6e064fb27bba.png)
Wordpress Version : 5.4.1
Please help to solved out this issue

**Comment by azaozz** [comment]
If I understand correctly you are asking why the "add blocks" button is disabled? It is because the title is selected. Press enter or click under it.
