### ISSUE TITLE
Typo: "Calssic"

### ISSUE THREAD

**Issue by La-Geek** [WordPress/classic-editor#12]
There is a typo in the strings:
> Change the %1$sCalssic Editor settings%2$s on your User Profile page.

https://plugins.trac.wordpress.org/browser/classic-editor/trunk/classic-editor.php#L456
also in
https://plugins.trac.wordpress.org/browser/classic-editor/trunk/classic-editor.php#L458

**Comment by azaozz** [comment]
Thanks, fixed in https://github.com/WordPress/classic-editor/commit/6f0687b837ea6d54b502ae7c9e3e5fe0820eb717.
