### ISSUE TITLE
Issue with WYSIWYG "visual button"

### ISSUE THREAD

**Issue by SoundServiceAU** [WordPress/classic-editor#122]
Hi,
For some reason, whatever page I go into to edit, it only brings up the text version and will not allow me to select "visual". As a side issue, the "help" button doesn't do anything either.
I have tested this in Chrome, Safari and Edge and it's the same problem - any help to fix it would be great.

**Comment by azaozz** [comment]
Sounds like js errors. Please look in the browser tools and report any errors on the support forum: https://wordpress.org/support/forum/how-to-and-troubleshooting/.
