### ISSUE TITLE
Call to Deprecated function add_option_whitelist

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/classic-editor#124]
The current version of the Classic Editor plugin (v1.5) is producing the following error on 5.5-beta2:

>Deprecated: add_option_whitelist is deprecated since version 5.5.0! Use add_allowed_options() instead. in /Users…/wp-includes/functions.php on line 4767

`add_option_whitelist()` is being called within `classic-editor.php`

**Comment by azaozz** [comment]
Thanks for opening this. The notice was fixed some time ago and will be in the plugin update for WP 5.5.

Fixed with https://github.com/WordPress/classic-editor/pull/123.

**Comment by maddisondesigns** [comment]
Fantastic! Thanks for that 👍

**Comment by suspectz** [comment]
@azaozz This appears to have been missed off the release.

**Comment by maddisondesigns** [comment]
Seems to have been fixed for me. I updated the Classic Editor plugin to the latest version (1.6) and the notice disappeared.
