### ISSUE TITLE
Duplicate links created on mobile devices

### ISSUE THREAD

**Issue by wpsmort** [WordPress/classic-editor#125]
There's a problem with creating links in the Classic Editor on a mobile device.  When I create a link and select the Open link in a new tab checkbox in the Link modal, the selected text is duplicated.

Steps to reproduce:

1. On a mobile device (I used an iPad and iPhone) create a post in Classic Editor
2. Add at least one word of text in the Visual editor
3. Select the text and click the link icon to display the Add Link modal 
4. Select an existing page/post to link to or type in a URL
5. Click the Link Options icon and select Open in new tab
6. Click Update and you should see the text has been duplicated and one instance of the text has the link

I've recorded a video showing this.  I used Chrome Dev Tools to simulate an iPad - https://a.supportally.com/lf3Mj8

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this is still a problem and has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
