### ISSUE TITLE
A deprecated function in WordPress 5.5 is still being used add_option_whitelist

### ISSUE THREAD

**Issue by sebastianmoran-mainwp** [WordPress/classic-editor#127]
`add_option_whitelist()` has been replaced with `add_allowed_options()`

https://github.com/WordPress/classic-editor/blob/258f56d4626e97061eee983f35a0f5be288cad29/classic-editor.php#L350

https://make.wordpress.org/core/2020/07/23/codebase-language-improvements-in-5-5/

**Comment by janboddez** [comment]
Looks like the fix will land in the next release: https://github.com/WordPress/classic-editor/pull/123.
