### ISSUE TITLE
add_action not work with classic editor

### ISSUE THREAD

**Issue by mhndm** [WordPress/classic-editor#128]
hello
why  **add_action( 'edit_post', 'my_function', 10, 2 );** don't work ?
its ok with box editor

function my_function($post_id, $post)
{
    
    
    $author = $post->post_author;
    $name = get_the_author_meta( 'display_name', $author );
    $email = get_the_author_meta( 'user_email', $author );
    $title = $post->post_title;
    $post_content = strip_tags($post->post_content);
    $post_image = get_the_post_thumbnail_url($post->ID,'full'); 
    $permalink = get_permalink($post->ID);
}

**Comment by azaozz** [comment]
Hmm, seems to be working properly here. Can see it run every time  post has been updated: https://developer.wordpress.org/reference/hooks/edit_post/.

In any case, don't think this has anythign to do with the Classic Editor plugin. That action is part of WP core, of there are problems with it please open a new trac ticket.
