### ISSUE TITLE
Should Classic Editor continue to disable the Gutenberg plugin?

### ISSUE THREAD

**Issue by azaozz** [WordPress/classic-editor#13]
Disabling of the Gutenberg plugin was added in Classic Editor mostly to test the functionality. However for version 1.0 (intended for WordPress 5.0) this doesn't seem necessary any more. People that would like to continue testing Gutenberg wouldn't need a separate plugin to disable it :)

@alexislloyd @pento @youknowriad thoughts?

**Comment by alexislloyd** [comment]
That makes sense to me but would want @youknowriad or @pento to confirm to make sure we’re not missing an edge case.

**Comment by youknowriad** [comment]
Makes sense.

**Comment by azaozz** [comment]
Thanks, will do (and I thought I'm the only one working on Sunday after RC...) :)

**Comment by azaozz** [comment]
Done in https://github.com/WordPress/classic-editor/commit/c69edfbda5fa7079a42b58e32685c4ee6a0b56e3.
