### ISSUE TITLE
WordPress 5.5 issues while editing

### ISSUE THREAD

**Issue by bpbeckett** [WordPress/classic-editor#130]
Hello - since updating to WordPress 5.5 the classic editor won't allow me to make certain edits;

1 - It won't allow allow editing the hyperlink to have pages open in new window. The window scrolling freezes when you try.
2 - Clicking on ADD MEDIA stopped working.
3 - Adding tags stopped working...including choosing the most used.

There may be more, but that was enough to force me to go back and forth between the terrible block editor and classic editor.

Thanks in advance for whoever can fix these!!!!

**Comment by emidez** [comment]
Hello,

The same thing happens to me as the user bpbeckett, in addition, I cannot modify the status, visibility, or the scheduling date of the post. I have checked disabling the plugin and then it works correctly with the wordpress panel.

Thank you for your attention and I hope that it is solved as soon as possible.

Regards.

**Comment by RalpManis** [comment]
Same here.

**Comment by bpbeckett** [comment]
This morning I reinstalled WordPress and it seems to be working find now.  I wonder if WordPress fixed something on the back-end but just didn't tell anyone.  Either way, it is now working.....for now anyway.

**Comment by azaozz** [comment]
> it seems to be working fine now.

Probably was "just a caching issue". These usually magically fix themselves :)

Closing this as a better place for support would be to post on the Classic Editor's support forum: https://wordpress.org/support/plugin/classic-editor/. There also are a lot of answered questions there.
