### ISSUE TITLE
issues with WordPress 5.5 update

### ISSUE THREAD

**Issue by juliecookies** [WordPress/classic-editor#131]
Since the update, many things using the Classic Editor plugin are broken. Can't switch from Visual to HTML. Can't load a template. Can't change the publish date. Can't add media. I understand from other users who are using blocks are not having this problem, as well as people who have not updated to the most recent version of Classic Editor are also not encountering this. Please send a fix.

**Comment by azaozz** [comment]
Most likely a js error. Please see the support forum for possible fixes: https://wordpress.org/support/plugin/classic-editor/.
