### ISSUE TITLE
Massive problem with WP 5.5

### ISSUE THREAD

**Issue by KristianRasmussenAlt** [WordPress/classic-editor#132]
Since I made the update, I have different issues with Block Editor when I want to switch between Heading and Paragraph. Also - Yoast SEO plugin and my View tracking plugin are located in the bar, instead of below the post and neither of them works.

**Comment by azaozz** [comment]
A better place to post this would have been either the Gutenberg plugin support forum (if you're using it), or the general WP support forum if you're talking about the block editor in WP. I'm afraid the Classic Editor plugin has little to do with this problem.
