### ISSUE TITLE
Unable to use Text Tab of Classic Editor with WP 5.5

### ISSUE THREAD

**Issue by charissa7** [WordPress/classic-editor#133]
We had to revert to the previous version of WordPress to be able to use the Text tab of the Classic Editor again. I use the text tab a lot, and frequently switch back and forth between that and WPBakery page builder. Do you know when this will be fixed? WPEngine support advised I check with Plugin support for updates until it's safe to update to WP 5.5. I usually disable Gutenberg/block editor (not a fan) so I really do need Classic Editor to work properly.

**Comment by azaozz** [comment]
Most likely a js error. Please see the support forum for possible fixes: https://wordpress.org/support/plugin/classic-editor/.
