### ISSUE TITLE
Read more tab doesn't work on classic editor

### ISSUE THREAD

**Issue by alexlaudano** [WordPress/classic-editor#134]
For some reason and after the latest updates, the "read more" tab doesn't apply. It goes to the last line of the post automatically (not where I decide to set it). Thanks

**Comment by azaozz** [comment]
Assuming you mean when you insert the tag in the Visual editor on the old Edit Post screen. Just retested this and seems to work properly here... Perhaps try in a different browser (to rule out browser extensions, etc.). If still the same, seems the next step would be to start disabling plugins one by one until you find which is doing this (if any).

**Comment by azaozz** [comment]
No reporter feedback for a long time. Assuming the issue was resolved.
