### ISSUE TITLE
Cannot switch between Visual and Text editors after WordPress 5.5 update

### ISSUE THREAD

**Issue by EzraSidran** [WordPress/classic-editor#135]
I am using Classic Editor 1.6,  WordPress 5.5. After the recent WordPress update Visual Editor no longer works.
Clicking on Visual does nothing.
![image](https://user-images.githubusercontent.com/69821933/90444853-4085f280-e0a4-11ea-9539-d63f36f8eb3e.png)

Help! I hate editing in HTML

**Comment by EzraSidran** [comment]
I just wanted to post that I found a temporary fix: “With the update to WordPress 5.5, a migration tool known as jquery-migrate will no longer be enabled by default. This may lead to unexpected behaviors in some themes or plugins who run older code. This plugin serves as a temporary solution, enabling the migration script for your site to give your plugin and theme authors some more time to update, and test, their code.” 

Downloading and installing that plug-in fixed the problems I was experiencing with 5.5.

**Comment by pedjas** [comment]
I have the same problem. After I did update of WordPress (to version 5.5) and this plugin (to version 1.6), it seems anything related to JavaScript became non functional.

**Comment by EzraSidran** [comment]
Use that fix I posted above. It works.

**Comment by arjunkomath** [comment]
I’m facing the a similar issue, the visual editor doesn’t seem to show at all. I’m always seeing text editor.

Things I tried:
- Reinstall wordpress
- Disable all plugins 
- Use default theme
- tried install the plugin @EzraSidran suggested

None of these seems to fix the issue.

**Comment by arjunkomath** [comment]
I found a similar report here: https://wordpress.org/support/topic/no-longer-working-with-wp-5-5/

**Comment by fabiventavoli** [comment]
Nossa nem sei como agradecer, funcionou instalando o plugin Enable jQuery Migrate Helper.
Muito agradecida @EzraSidran

**Comment by azaozz** [comment]
Yes, most likely a js error that may be coming from an old script that needs updating. There are several threads in the support forum about similar cases.

This plugin only enables the old Edit Post screen, it doesn't change it in any way. All the code is in WordPress itself. JavaScript errors on the old Edit Post screen are (should be) handled on the support forum, or on core trac. The Classic Editor plugin cannot fix these :)
