### ISSUE TITLE
Plugin breaks Menu item-type in Appearance > Menu

### ISSUE THREAD

**Issue by abuyoyo** [WordPress/classic-editor#138]
When adding post or page menu items to the menu, the `item-type` field should show `Post` or `Page`.
When Classic Editor plugin is enabled, the `item-type` field shows `Classic editor` or `Block editor` instead.

This is both useless information on the Menu page - the type of editor used is not important. And it obfuscates relevant information - what type of menu item it actually is - post or page.

Also `item-type` should use title-casing. But that last point should become moot once this is fixed.

**Comment by azaozz** [comment]
Could you give some more info: Which menu? The wp-admin (left-hand side) or the dotdotdot menu in Gutenberg, or perhaps I'm misunderstanding something?

**Comment by azaozz** [comment]
No reporter feedback for a long time. Assuming the issue was resolved.
