### ISSUE TITLE
After update wordpress 5.5.1 html (text) mode not working

### ISSUE THREAD

**Issue by mohit-natu** [WordPress/classic-editor#140]
After update WordPress 5.5.1 html (text) mode not working. I can only click on visual tab. When I press text tab, not able to clicking on it.
![Screenshot_2](https://user-images.githubusercontent.com/53134581/92435462-0057f280-f1c0-11ea-8c77-4a3906b6a5c2.png)

**Comment by azaozz** [comment]
Sounds like a js error somewhere on the page. If that's still the case, please post to the support forum and paste the error.

**Comment by azaozz** [comment]
Seems no reporter feedback for a long time. Assuming the issue was resolved.
