### ISSUE TITLE
Publish or Save doesn't appear on my Classic Editor 

### ISSUE THREAD

**Issue by mwlanguage** [WordPress/classic-editor#141]
So this is how Classic editor should look 
![image](https://user-images.githubusercontent.com/71163665/92986689-beae9c80-f48a-11ea-9187-3aa09770df14.png)

But mine looks like this (it is missing the Publish button. Does anyone know what is going on
![image](https://user-images.githubusercontent.com/71163665/92986724-ebfb4a80-f48a-11ea-9542-4e8bcea34fbc.png)

I would really appreciate the help. It would mean the WORLD to me

**Comment by azaozz** [comment]
Hmmm, that's strange. The "publish" metabox cannot be hidden from Screen Options. Can you look at the source HTML to see if the HTML for it is still there, and it is hidden just visually, with CSS? Can also look in the browser tools; see if it is above the Page Attributes metabox. If yes, see where that CSS comes from. If no... Guessing there may be a plugin that filters it, but no idea why, or which plugin may do that. Next step is to start disabling plugins one by one until you get to the culprit.

**Comment by azaozz** [comment]
Seems no reporter feedback for a long time. Assuming the issue was resolved.
