### ISSUE TITLE
Editor sidebar is not functioning properly

### ISSUE THREAD

**Issue by hehafner** [WordPress/classic-editor#143]
I recently update the classic editor to Version: 1.6 and now functions in the right sidebar are not working. My client uses the schedule function but since I upgraded this plugin it doesn't work. Once I deactivated the plugin, it works fine. On other sites that I manage, I haven't updated yet and the plugin works fine. Is there a fix coming up on this? And, where can I get the previous version so I can roll back?

Thank you

**Comment by Capitanbasa** [comment]
> I recently update the classic editor to Version: 1.6 and now functions in the right sidebar are not working. My client uses the schedule function but since I upgraded this plugin it doesn't work. Once I deactivated the plugin, it works fine. On other sites that I manage, I haven't updated yet and the plugin works fine. Is there a fix coming up on this? And, where can I get the previous version so I can roll back?
> 
> Thank you

what wordpress version are you using?

**Comment by azaozz** [comment]
This plugin doesn't change anything on the old Edit Post screen, it just lets the users select it. The actual code there is still part of WordPress.

Do you see any js errors in the browser tools? If yes, and if they are coming from core, please open a ticket for WordPress. If the errors are from a plugin or the theme, please post to the support forum.

**Comment by azaozz** [comment]
Seems no reporter feedback for a long time. Assuming the issue was resolved.
