### ISSUE TITLE
Accessibility: Screenreader Not Picking Up New Post Dropdown in WP-Admin

### ISSUE THREAD

**Issue by sdixon194** [WordPress/classic-editor#145]
When using a screenreader such as JAWS and NVDA, it seems they don't pick up the dropdown menu after "New Post" so that one can select Block Editor or Classic Editor in WP-Admin. Issue seems to occur in Microsoft Edge, but doesn't seem to be reproducible in Chrome.

![selecting-classic-editor-from-new-post-dropdown](https://user-images.githubusercontent.com/33553323/95900124-74f1f400-0d5f-11eb-8227-bf62a47352c9.png)

**Comment by azaozz** [comment]
Hi @sdixon194, this drop-down is neither in Classic Editor, nor in Gutenberg. I think it was part of the initial version of Classic Editor more than two years ago, but was removed as it didn't work well/was not intuitive. It was also in Gutenberg roughly at the same time, but was removed years ago from there too.

Currently this screen looks like this (with both Classic Editor and Gutenberg enabled):

![no-dropdown](https://user-images.githubusercontent.com/743931/95954900-b4bee700-0e04-11eb-9f54-06e256f0df1b.png)

Perhaps you're using a very old version of the plugin, or another plugin that adds it?

**Comment by sdixon194** [comment]
Huh strange, seems WordPress.com simple sites (no plugins installed) show the old dropdown still.
