### ISSUE TITLE
Throws a warning when updating post and etc

### ISSUE THREAD

**Issue by kiwimarc** [WordPress/classic-editor#147]
![image](https://user-images.githubusercontent.com/17028946/96707286-f5d07180-1397-11eb-9221-656a7ea2b48f.png)
I'm using wordpress version 5.5.1 and classic editor version 1.6.
When I want to update a page. post or etc it throws warning showed in the image. It does save the changes, but I would still prefer if the warning wasn't popping up.

**Comment by jeffpaul** [comment]
@kiwimarc does that message also appear when saving or publishing a post/page/etc or just updating one?

**Comment by kiwimarc** [comment]
It only comes up if I previous had saved it or published it.

**Comment by jeffpaul** [comment]
@kiwimarc I'm not able to reproduce that.  Can you share other plugins that are installed in case one of them is contributing to this?

**Comment by kiwimarc** [comment]
- Advanced Custom Fields
Version 5.9.1
- Checkout Field Editor for WooCommerce
Version 1.4.4
-  classic editor
Version 1.6
- Companion Auto Update
Version 3.7.0
- Contact Form 7
Version 5.3
- Cronjob Scheduler
Version 1.40.1
- Elementoir
Version 3.0.12
- Essential Addons for Elementor
Version 4.3.3 
- EventON
Version 2.9.1
- EventON - Dynamic Pricing
Version 0.6
- EventON - Event Tickets
Version 1.8.6
- EventON - Ticket Variations & Options
Version 0.8 
- FileBird
Version 3.9 
- Gutenberg
Version 9.2.1 
- Import Users from CSV
Version 1.0.1
-  Insert Pages
Version 3.5.7
- Insert PHP Code Snippet
Version 1.3.1 
- Ivory Search
Version 4.5.9 
- Max Mega Menu
Version 2.9.1
- Members
Version 3.1.3
- Menu Image
Version 2.9.7
- My Database Admin
Version 1.1.21
- Peter's Login Redirect
Version 2.9.7
- Photonic Gallery & Lightbox for Flickr, SmugMug, Google Photos & Others
Version 2.45 
- PublishPress Capabilities
Version 1.10.1
- Recent Posts Widget Extended
Version 0.9.9.7 
- Redirection
Version 4.8
- Relevanssi
Version 4.8.3
- Role Based Price For WooCommerce
Version 3.3.7
- Role Based Redirect
Version 1.2
- Simple Local Avatars
Version 2.1.1 
- Sponsors Carousel
Version 4.02
- Username Changer
Version 3.2.2
- WooCommerce
Version 4.6.1 
- WooCommerce Admin
Version 1.6.2
- WooCommerce E-Transactions Payment plugin
Version 0.9.8.6
- WooCommerce Memberships
Version 1.16.5
- WooCommerce Menu Cart
Version 2.9.6
- WP Latest Posts
Version 4.8.4

**Comment by Capitanbasa** [comment]
> * Elementoir
>   Version 3.0.12

are you using both elementor and classic editor? i mean sometimes you use elementor and sometimes classic editor?

**Comment by kiwimarc** [comment]
Yes I use both.

**Comment by Capitanbasa** [comment]
> Yes I use both.

have you try clearing your browsers cache

**Comment by azaozz** [comment]
Hmmm, this is a pretty strange error message. The second line: "The comment changes you made will be lost." doesn't exist in WP, and (as far as I see) it's not in any plugin that's in the repo. Think the key to finding what causes this is to find the plugin that contains that line.

**Comment by kiwimarc** [comment]
> > Yes I use both.
> 
> have you try clearing your browsers cache

Yes, I have tried it on:
Safari - Mac and Iphone
Chrome - Windows and android
Edge - Windows

**Comment by kiwimarc** [comment]
> Hmmm, this is a pretty strange error message. The second line: "The comment changes you made will be lost." doesn't exist in WP, and (as far as I see) it's not in any plugin that's in the repo. Think the key to finding what causes this is to find the plugin that contains that line.

The problem is that I only get this error message when classic editor is active. If i deactivate it, the error disappears.

**Comment by azaozz** [comment]
> I only get this error message when classic editor is active.

Perhaps I'm misunderstanding something. Where exactly do you see this error? 
- On the new Edit Post screen (block editor/Gutenberg).
- On the old Edit Post screen (classic editor/TinyMCE).
- Somewhere else?

**Comment by kiwimarc** [comment]
> > I only get this error message when classic editor is active.
> 
> Perhaps I'm misunderstanding something. Where exactly do you see this error?
> 
> * On the new Edit Post screen (block editor/Gutenberg).
> * On the old Edit Post screen (classic editor/TinyMCE).
> * Somewhere else?

On the old Edit Post screen (classic editor/TinyMCE) and on the new Edit Post screen (block editor/Gutenberg) if the plugin is active

**Comment by azaozz** [comment]
@kiwimarc I can't figure out where that error message is coming from. Could you download all of your plugins (if you don't already have local copies), then run a text search on all files.

Looks like TinyMCE may be initialized on a textarea that is intended to edit comments, perhaps? And after the initialization somehow that textarea value is changed. That's just a guess, to get to the bottom of this will need to look at the code doing it :)

**Comment by themc-george** [comment]
I see it in wp-admin/js/edit-comments.js

**Comment by kiwimarc** [comment]
> @kiwimarc I can't figure out where that error message is coming from. Could you download all of your plugins (if you don't already have local copies), then run a text search on all files.
> 
> Looks like TinyMCE may be initialized on a textarea that is intended to edit comments, perhaps? And after the initialization somehow that textarea value is changed. That's just a guess, to get to the bottom of this will need to look at the code doing it :)

Oh wow, I have first now seen that you replied.
But as @themc-george  says its in the   wp-admin/js/edit-comments.js

**Comment by themc-george** [comment]
i created a bug ticket: https://core.trac.wordpress.org/ticket/55332

**Comment by kiwimarc** [comment]
@themc-george Great, I will close this ticket because its wordpress that have the issue :)
