### ISSUE TITLE
Classic Editor is blocking slug information being displayed in Yoast

### ISSUE THREAD

**Issue by visualtribe** [WordPress/classic-editor#149]
Your Classic Editor is stopping the display of the text in the slug form field of Yoast. If the plugin is disabled, the information appears. As soon as it is activated the information field goes blank. Version 1.6 Please fix

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this is still a problem and has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
