### ISSUE TITLE
Test: make the "Open the last editor used..." standard behavior and remove the setting for it

### ISSUE THREAD

**Issue by azaozz** [WordPress/classic-editor#15]
This will promote the "best behavior" of always using the same editor for each post and simplify the settings UI a bit.

Follow-up from https://github.com/WordPress/classic-editor/issues/9#issuecomment-443489913.

**Comment by azaozz** [comment]
Added in https://github.com/WordPress/classic-editor/commit/de3213bbb2bc3e471774566e4dd23bc088b81ff6.

Current UI:

![settings-admin](https://user-images.githubusercontent.com/743931/49339250-dd39ff80-f637-11e8-94ee-c1c33b6fca27.png)
Admin settings.

![settings-user](https://user-images.githubusercontent.com/743931/49339254-e75bfe00-f637-11e8-916d-3720103e861a.png)
User settings.

![posts-lost-table](https://user-images.githubusercontent.com/743931/49339257-ef1ba280-f637-11e8-9881-fecc459b26f0.png)
Posts screen (list table).

**Comment by azaozz** [comment]
Still TBD: currently the additional post state is shown for all posts. Would it be better to show it only for posts that will open in the "other" non-default editor? I.e. if the user selected Block Editor, and some posts were edited in Classic, show "Classic Editor" in the lists-table only for them.

cc: @alexislloyd, @youknowriad, @kwight

**Comment by youknowriad** [comment]
Just some questions here:

- If the user is not allowed to switch editors, will it still open the post in the "alternative" editor? Seems to me like it should use the "enforced" editor in this case.

- I think I prefer to show for all posts, but I'll defer to @alexislloyd foor thoughts design wise.

**Comment by azaozz** [comment]
> If the user is not allowed to switch editors, will it still open the post in the "alternative" editor? Seems to me like it should use the "enforced" editor in this case.

Yes, agree it should always use the "enforced" editor. Also, when the user is not allowed to switch editors, it doesn't save the editor used for each post (as it cannot be changed).

**Comment by azaozz** [comment]
Also added in https://github.com/WordPress/classic-editor/commit/1bc87018bb1e576b5a668e3ff0ae00ba639dce9d

- Add a helper function and a filter to get the enabled editors by post type.
- Add a helper function and a filter to get the enabled editors by post.
- Use the above in the UI when outputting links, metaboxes, etc.
- Add some subtle style for the post state when an editor is enforced.

It lets other plugins disable editors by post type or by post, and fixes handling of CPTs.

**Comment by coreymckrill** [comment]
With `Default editor` set to `Block` and `Allow users to switch` set to `Yes`, the Posts list is showing "Block" for the state of posts that were published via the Classic editor before Gutenberg was installed. Is this the intended behavior?

My expectation was that for legacy posts, the "last editor used" would be the Classic editor.

**Comment by azaozz** [comment]
@coreymckrill thanks for testing! :)

> the Posts list is showing "Block" for the state of posts that were published via the Classic editor before Gutenberg was installed.

Yes, it shows the editor that will be used to edit the post, not the editor that was used before. By default WP opens all older posts in the Gutenberg/Block Editor (when it is set as default or without this plugin). Don't think we should change that.

We have two options there:
1. Show "editor state" for all posts. Current behavior.
2. Show state only for posts which will open in the alternative editor (saved previously or forced by plugins or CPT settings).

There is a third option: show state only for posts where we have saved the editor, but that will be incomplete/confusing as some posts (or post types) will still open in the alternative editor.

I'm still 50/50 on which way is best :) # 1 is really reassuring. The users will always know what will happen before clicking on the edit link. At the same time it is different that the similar feature in Gutenberg. It shows the "previous editor state" there, i.e. posts that were edited with Gutenberg at some point. As far as I understand the "Gutenberg state" is shown to warn the user not to edit posts with blocks in the classic editor. That's not needed here as this plugin will always open posts edited in the Bock Editor with the Block Editor.

# 2 also looks/works very well. It's not as reassuring as # 1 but is more subtle/toned down as it shows a lot less often. The purpose of showing a "post editor state" changes there a bit. Instead of being a declaration: "This post will be edited in that editor" it becomes more of a warning: "This post will be edited in the alternative editor". In the longer term that's probably better.

What do you think? :)

**Comment by melchoyce** [comment]
Quick UI note — the yes/no radio options should be vertical, like:

![image](https://user-images.githubusercontent.com/2846578/49471370-aea85a00-f7da-11e8-8e2c-e2c71e16d948.png)

**Comment by azaozz** [comment]
> the yes/no radio options should be vertical

Done in https://github.com/WordPress/classic-editor/commit/b75b3bf0ede6a8c5378b62de341abe3bf9f61e9d.

**Comment by azaozz** [comment]
Latest screenshots:
![admin-settings](https://user-images.githubusercontent.com/743931/49480625-15a42e00-f830-11e8-8911-95b6c6617338.png)

![user-settings](https://user-images.githubusercontent.com/743931/49480632-1a68e200-f830-11e8-9338-880c1cc97a80.png)

![block-editor-metabox](https://user-images.githubusercontent.com/743931/49480633-1dfc6900-f830-11e8-861e-5f0abc0168c5.png)

![classic-editor-metabox](https://user-images.githubusercontent.com/743931/49480635-205ec300-f830-11e8-8bc1-406a5d73b043.png)

**Comment by melchoyce** [comment]
In that last screenshot, can you update the margin on the notice to `1em inherit 0;`?

**Comment by luciano-croce** [comment]
@azaozz

I think that the warning message on the "about" page is not appropriate (also the message on the dashboard is not appropriate). I think that another position is better for this message.

- The "about" page is not immediate for the users, except after the installation or the upgrade.
- An administrator could inhibit the access to this page.
- In another position, the message is less intrusive and misleading: some users, for example, might think of an error in its WordPress, and/or its own installation/upgrade.

For example:

- User Profile (compatible with all types of user capacity) best choice IMHO
- Option settings page of the Cassic Editor
- Plugin Page (when the Classic Editor is activated, this message is displayed - most common behavior)
- Another position but not the "about" page or the "dashboard"

**Comment by azaozz** [comment]
> The "about" page is not immediate for the users, except after the installation or the upgrade.

Exactly. The intention is to warn the users right after they upgrade WordPress and not do "annoyingly repeating" warnings elsewhere.

Not sure why you think that warning may be misleading. Keep in mind that admins can "lock" the editor choice. Then the users won't be able to do anything about it :)

**Comment by luciano-croce** [comment]
> Keep in mind that admins can "lock" the editor choice. Then the users won't be able to do anything about it.

And also the warning disappears?

It's ugly to view...

Is it not possible change the position totally, for example completely at the top of the about page?

What do you think about it?

**Comment by azaozz** [comment]
Do you have a screenshot? :)

**Comment by luciano-croce** [comment]
I have a screenshot (one moment plese) but not the code...

![classic-editor-warning-message-totally-on-top](https://user-images.githubusercontent.com/19188077/49512430-37340280-f88e-11e8-892f-55bb67778567.png)

**Comment by luciano-croce** [comment]
With appropriate integration the result is more beautiful of this screenshot...

**Comment by azaozz** [comment]
Hmm, not sure what's going on there but I see the warning under the title, like in the first screenshot:

![warning](https://user-images.githubusercontent.com/743931/49513639-56d12800-f89a-11e8-889d-79e1211a7748.png)

(Note that the styling was fixed by melchoice a bit earlier).

This works somewhat "hacky" in WP. The messages are outputted above the title, and then moved below it on page load with jQuery. That's been around forever... Perhaps see if there are any JS errors on that page?

**Comment by luciano-croce** [comment]
It's just my idea, I do not have the code for this, in fact. All the tests I've done, in fact, have always moved it under the title. Anyway it's just my idea, you decide what is best to do, for me it's okay what you decide.

**Comment by azaozz** [comment]
All is done. The warning looks good too.
