### ISSUE TITLE
PHP code in page is always commented

### ISSUE THREAD

**Issue by johnnyontheweb** [WordPress/classic-editor#150]
Hello all,
when editing pages with classic editor in Visual tab, on saving all the php code I have inserted in the document are commented.
For example 
`<?php if(is_user_logged_in()) : ?>`
 becomes `<!--?php if(is_user_logged_in()) : ?-->`

Is it a way to avoid this happens every time? I understand this can happen for a security reason, but I have legacy pages that need these line to be kept unaltered. 
thanks in advance

**Comment by johnnyontheweb** [comment]
Anyone? This issue still persists in actual version

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this is still a problem and has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.

**Comment by johnnyontheweb** [comment]
Hello,
not very useful as answer after 3 years and a half, anyway better than nothing. I'll try and let you know, thanks.
