### ISSUE TITLE
Right scrollbar is not displayed in visual mode

### ISSUE THREAD

**Issue by sasapurin** [WordPress/classic-editor#151]
In visual mode, the height of the entry field is maximized so that the right scroll bar is not displayed.
When I write an article and the whole thing scrolls, the menu buttons scroll together, which reduces usability.
There is no problem in text mode.
Is it possible to specify the height of the entry field? 

WordPress Version 5.6. 
Classic Editor.

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this is still a problem and has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
