### ISSUE TITLE
"Visualize" and "Save as Draft" buttons not working

### ISSUE THREAD

**Issue by Autoentusiastas** [WordPress/classic-editor#152]
Dears, 
"Visualize" and "Save as Draft" buttons are not working properly.
"Visualize" button is inert, not working. Visualization is not provided. 
"Save as Draft" is opening the visualization in a new window. 

I have already deleted the plugin and reinstaled, however the problem continues. 

Using the Native Wordpress the buttons work properly.

![Buttons](https://user-images.githubusercontent.com/78314336/106391566-d2708600-63cc-11eb-9457-2ece981a51f1.png)

Best regards

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen caused by another plugin, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.
