### ISSUE TITLE
<span class="classic-editor-forced-state"> displayed in Customizer when editing the menu

### ISSUE THREAD

**Issue by qtxh** [WordPress/classic-editor#153]
![span-displayed-in-customizer](https://user-images.githubusercontent.com/64882969/106462523-2f556480-64d1-11eb-9d7d-9195b40f5ad4.png)

When editing the menu in Customizer, `<span class="classic-editor-forced-state">` was displayed in the screen. It seems that the problem was introduced in [classic-editor.php#L853](https://github.com/WordPress/classic-editor/blob/e283108eb74fa146cbf54dbb60b0344ae496f9bb/classic-editor.php#L853) and L856?

**Comment by cmllr** [comment]
I guess the answer will be no, but did you manage to resolve your issue @qtxh? I am currently facing the same issue. Thank you.

**Comment by azaozz** [comment]
Think this was a problem in core and was fixed some time ago. Sorry for closing this so late.
