### ISSUE TITLE
Default font

### ISSUE THREAD

**Issue by Spaceman50** [WordPress/classic-editor#156]
I have tried to alter the default font in the Polaris Writer Theme to Book Antiqua but it appears to stay as Georgia.

Is this because the Wordpress Classic Editor has  default font?

If so how do I change it to Book Antiqua please?

Thnaks,

Mark

**Comment by azaozz** [comment]
Seems perhaps this can be changed/set by another plugin? The Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.
