### ISSUE TITLE
Wordpress Classic Editor Plugin - Help!

### ISSUE THREAD

**Issue by ghost** [WordPress/classic-editor#16]
I came across this site while trying to figure out how to revert back to the Wordpress classic editor. I want to work on a blog post today but I logged on to find the editor has totally changed overnight. I have no idea how to use it, or how to revert back to the classic editor. From googling I came across this site and a possible classic editor plugin, but I have no clue how to utilise it. I use the free version of Wordpress, I don't know if that makes a difference. I'm sorry if this is not what this site is for, but if anyone can guide me through installing this plugin I'd be very grateful.

**Comment by azaozz** [comment]
For help with using this plugin (or any plugin) best would be to post to the support forum: https://wordpress.org/support/plugin/classic-editor.

You can install any WordPress plugin by going to the "Plugins -> Add New" screen as long as you have admin access to the site. If you don't, ask an admin to install it :)
