### ISSUE TITLE
Text view loses focus

### ISSUE THREAD

**Issue by froginperil** [WordPress/classic-editor#161]
I have done some open source devel. I understand the challenges. Admittedly this is not a priority issue.

Having said that I always write posts in text mode because I use a variety of CSS classes and - frankly - because I am an old fart. Very often, in text mode, the focus shifts from the editor to other parts of the screen. Entering a couple of carriage returns to make html easier to understand scrolls everything surrounding the page being edited. I also use KDE hotkeys to enter styles (bold, italic, underline, etc). This, too, often creates a loss of focus. I hope that I have explained this properly.

Thanks for all you've done and continue to do.

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this is still an issue and has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
