### ISSUE TITLE
Odd background color

### ISSUE THREAD

**Issue by greglow-sdu** [WordPress/classic-editor#162]
Hi Folks,

I installed the Classic Editor plug in on a new site today. The theme was the standard Twenty Twenty-One theme. That theme defaults to a green background. If I set the theme to a different color background (like light yellow), I notice the background in the classic editor is green. Is that what's expected? I'm guessing it picks it up from the default theme color? Would be great if it used the same color as the theme.

Regards,

Greg

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
