### ISSUE TITLE
Conflict with Elementor

### ISSUE THREAD

**Issue by ccstinger** [WordPress/classic-editor#163]
I was debugging our site, and came across the following exception in the console:

> Uncaught TypeError: $element.elementorWaypoint is not a function

Reached out to Elementor who did some testing and found that when de-activating the class-editor this exception went away.  Bringing this to your attention as I assume there are a lot of people who use Elementor + Class Editor.

Han

**Comment by azaozz** [comment]
Assuming this was fixed long ago. Sorry for closing the issue so late.
