### ISSUE TITLE
Visual tab deleting changes

### ISSUE THREAD

**Issue by kendal77** [WordPress/classic-editor#165]
> Did some editing that had to be done in Text tab.  saved updated and all that jazz, and if I open it in text all the changes are there but when I click on visual tab, all the changes are deleted.  

Here is a video of it happening... well can't do that cause it is too big.

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
