### ISSUE TITLE
Make this compatible with Dark Mode Plugin

### ISSUE THREAD

**Issue by drkhodakarami** [WordPress/classic-editor#168]
Hi
Take a look at dark mode plugin
https://wordpress.org/plugins/wp-dark-mode/
This will make the admin panel dark and easier for those of us who do lots of posting and site activity, how ever, if you read this post about this plugin >>
https://www.wpbeginner.com/plugins/how-to-add-dark-mode-to-your-wordpress-admin-dashboard/
you will find that gutenburg editor is being supported for dark mode how ever, this classic editor, has no way of getting the dark mode and for people like me who write article all the time during day, it makes my eyes tired a lot faster compared to when we work with darker interfaces.

Please make this awesome editor compatible with the plugin or provide a dark mode setting by your selves.

Thanks

**Comment by azaozz** [comment]
Sounds like this is a request for the (old) Edit Post screen, not for this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it looks or works. Seems this needs to be implemented in the Dark Mode plugin.
