### ISSUE TITLE
Image center align is not applied.

### ISSUE THREAD

**Issue by mongdolappa** [WordPress/classic-editor#169]
I aligned the image to the center. However, in the actual page, the image is only aligned to the left.
No matter how many times I test it.
Please check it once.
My theme is sinatra.

**Comment by steamboatid** [comment]
have you test it with another theme?

**Comment by jordesign** [comment]
I've just tested this - and it occurs in newer Block Themes, but not in older themes. It seems themes need to include the CSS styles to make sure the image is aligned on the front end.

**Comment by jordesign** [comment]
For anyone coming here looking for a solution until this is resolved - it looks like adding this CSS code will help

`/* Center Align Images */
img.aligncenter {
    clear: both;
    display: block;
    float: none;
    margin-right: auto;
    margin-left: auto;
    text-align: center;
}`

**Comment by azaozz** [comment]
Yea sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this still happens and has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
