### ISSUE TITLE
WordPress 5.8 duotone

### ISSUE THREAD

**Issue by theamnesic** [WordPress/classic-editor#176]
Hi!

WordPress 5.8 introduce new Gutenberg functionalities, but with Classic editor we don't need the `<style id='global-styles-inline-css' type='text/css'>` in the header and the `wp-duotone` SVG in the footer.

Maybe the plugin should remove this ?

Edit : here's the topic on [wordpress.org](https://wordpress.org/support/topic/disabling-gutenberg-duotone-filter/)

**Comment by azaozz** [comment]
Not sure it would be a good idea to remove anything that is needed for the block editor. The Classic Editor plugin allows interchangeable editing with both editors, "breaking" something needed by the block editor won't be good :)
