### ISSUE TITLE
Button einfügen in Beitrag

### ISSUE THREAD

**Issue by evamaria22** [WordPress/classic-editor#177]
Hallo,
Nach dem letzten Update auf 5.9 lässt sich kein neuer Button mehr in einen Beitrag einfügen.

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this still happens and has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
