### ISSUE TITLE
Authors Do Not Show in Dropdown

### ISSUE THREAD

**Issue by nerdnestmedia** [WordPress/classic-editor#178]
Hello!
We are having an issue with Classic Editor. When Classic Editor is active, our list of Authors in Posts does not show any Authors, only Administrators. I was able to turn off this plugin, and the issue is resolved. Is there any way to fix this issue without having to deactivate classic editor?

Thanks!

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this still happens and has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
