### ISSUE TITLE
Image insert into post is not working

### ISSUE THREAD

**Issue by ihftech** [WordPress/classic-editor#179]
What I have done to fix these issues are:
updated htaccess file
deactivated all plugins if there were any issue
tried fresh/reinstalled WordPress

none of this worked :(

Really wired, don't know why image insert into post not loading image

I am attaching a video file URL to see the problem
https://www.dropbox.com/s/4un96rfi4tswtqz/inser%20into%20image.avi?dl=0

**Comment by davidjonesiran** [comment]
Sometimes when I use it, the site does not load properly, please update it; i will solve it too, thanks

**Comment by ihftech** [comment]
everything has been updated

**Comment by azaozz** [comment]
Seems this may have been a (JS?) bug in another plugin? It's unrelated to Classic editor as this plugin only enables the old Edit Post screen, nothing more.
