### ISSUE TITLE
Add "Default Editor" Modes Settings to Network Admin

### ISSUE THREAD

**Issue by mrjarbenne** [WordPress/classic-editor#18]
When the Classic Editor plugin is Network Activated on Multisite, it would be helpful to be able to control the new "Default Editor" settings (from https://github.com/WordPress/classic-editor/issues/9) at a Network admin level, to further manage the roll out of the Block editor on a network of sites. 

Basically having the same controls that are available in Settings/Writing, available within the Settings menu in the Network Admin, to force a default selection down to the site level. 

This might be a separate ticket: this would be a good location for an additional toggle to decide the default settings on new sites, in instances where new sites will use the block editor while existing sites have an opportunity to migrate over more slowly.

**Comment by mrjarbenne** [comment]
Maybe I'm an edge case, but it's the third option I'm looking for: 

1. Currently when the plugin is activated on Multisite, Classic Editor is selected as the default, with the option for site admins to opt into the Block Editor, and to allow their site users to do the same. 

2. Forcing the Block editor is equivalent to not activating the plugin. There is no use-case there. 

3. Activating the Classic Editor, and turning off the ability for anyone to opt into the Block Editor across the network is what is missing now that the "default editor" options are available. (I could just hold onto a previous version of the plugin, but my case might be more prevalent than I imagine, so I thought it was worth posting the issue.)

I want to be able to upgrade to 5.0, but hold off on the block editor until a couple more of our plugins are compatible, so that the first experience with the new editor is positive; then in phase two, allow users to opt into the block editor (current functionality of the master branch of the classic editor plugin when network enabled), to then eventually force it on the remaining users at a point in time to be determined. 

As I investigate further, it could be that a simple mu-plugin like this gets me there until I'm ready to provide site admins with an option to opt in: 

`add_filter('use_block_editor_for_post', '__return_false');`

This snippet seems to work in the current 5.0 RC. Feel free to close this issue if providing a UI for this option is out of scope. I know that the default editor settings have already created a bit of creep, but they are certainly appreciated to help us move forward at our own pace.

**Comment by mikenolan** [comment]
Currently I've got a mu-plugin with this but I've not updated against the planned changes to the classic-editor plugin:

```
add_filter( 'option_classic-editor-replace', 'ehu_gutenberg_classic_editor');

function ehu_gutenberg_classic_editor($value)
{
    if ( is_super_admin() ) {
        return 'no-replace';
    } else {
        return 'replace';
    }
}
```
This forces non-network admins to have the classic editor while network admins can turn on access to Gutenberg per site. As we test across our site we'll need to add in the ability to enable for each site.

**Comment by azaozz** [comment]
@mikenolan this will reset the option to always "replace" (i.e. use Classic Editor), but there is another one now: `classic-editor-allow-users` whether site users can choose the editor too.

There is also a filter to preset the options and disable the UI, `classic_editor_plugin_settings`: https://github.com/WordPress/classic-editor/blob/master/classic-editor.php#L100. Best to use it for this :)

**Comment by azaozz** [comment]
This should work fine:

```php
add_filter( 'classic_editor_plugin_settings', 'ehu_gutenberg_classic_editor' );
function ehu_gutenberg_classic_editor( $value ) {
	return array(
		'editor' => 'classic', // Accepted values: 'classic', 'block'.
		'allow-users' => false,
	);
}
```

**Comment by luciano-croce** [comment]
Very good! :)
