### ISSUE TITLE
Classic Editor

### ISSUE THREAD

**Issue by VycheslaVV** [WordPress/classic-editor#180]
Здравствуйте. Криво стал работать плагин **Classic Editor. (видео, картинки) Переустановка не помогла. В чем может быть проблема, где посмотреть, что сделать?**

На сайте устанавливал граббер (название не помню) - удалил. Вероятно после этого появились проблемы: видео (в **Classic Editor) - не перематывается и не устанавливается в центре страницы. Картинки **(в **Classic Editor) - не меняют размер, если "потянуть за уголок". При написании меток выпадают уже ранее набранные, но при нажатии на них - не встают в свое поле.** Плагин версии: 1.6.2

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this still happens and has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
