### ISSUE TITLE
Where is Version 1.7?

### ISSUE THREAD

**Issue by TheSmartDude** [WordPress/classic-editor#181]
Changelog talks about Version 1.7 an "ready for WP 5.9" but i can't find 1.7 in any repository. So ... where is it?

**Comment by willemb2** [comment]
It still hasn't been published on wordpress.org and [users are getting worried](https://wordpress.org/support/plugin/classic-editor/) about the lack of updates.

**Comment by azaozz** [comment]
Think this was a typo. Latest version as of April 2023 is 1.6.3.
