### ISSUE TITLE
Classic Editor Spacing Issue

### ISSUE THREAD

**Issue by Dk12121212** [WordPress/classic-editor#184]
Hello Team,

While using the classic editor in our posts area we have seen that after adding video in post content and toggling between text and 
visual editor &nbsp; is automatically getting added in the content area. please check the video.
https://www.loom.com/share/628998c3d2ec49b5afc181215dbde32c

I have created a separate WordPress with the default theme and replicated the issue on this site.
http://fmmprojects.com/classic_editor/wp-admin
Username: admin
Password: a
please update the post and again toggle the visual and text mode. you ca see that &nbsp; is getting added
http://fmmprojects.com/classic_editor/2022/07/05/hello-world/

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
