### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by editegg** [WordPress/classic-editor#185]
I'm hoping someone can advise me with a 404 error on WordPress when I create a new portfolio or page to add new work to my website.

When I create a new portfolio or page and I click on any of the columns under "portfolio page settings" or "page settings" instead of the column opening up, I get redirected to my website and a 404 error message saying "we couldn't find the page you were looking for" appears.

This has been happening for a couple of months now. Everything is up date including the PHP and we've done everything our provider has suggested but it's still not fixed.

I contacted a WordPress forum and they suggested it sounds like an issue with a plugin or a theme and to contact the support from those instead so I'm hoping you can advise.

Thanks!

**Comment by azaozz** [comment]
Seems unrelated to the Classic Editor plugin?

If this has been tested with all plugins disabled, please feel free to open a Trac ticket with the full description and how to reproduce it.
