### ISSUE TITLE
Child categories not intended on post edit screen

### ISSUE THREAD

**Issue by web1100manager** [WordPress/classic-editor#186]
On the post edit screen, categories are not listed hierarchal. Child categories appear at the same level as parent categories until one is selected, then it appears under the parent and intended.  This has been tested on the twenty twenty-two theme with all other plugins disabled.

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
