### ISSUE TITLE
Block Editor is not reactivated when Plugin is inactive

### ISSUE THREAD

**Issue by larsactionhero** [WordPress/classic-editor#191]
Hi there, 

i'm running a  WP 6.1 installation with a custom-build theme (Underscore, ACF and so on.).

For debugging purposes, i've deativated the classic editor plugin and wanted to see the content appearing in the block editor. 
But if the plugin is inactive (or even not installed at all), WP is still forced to use the classic editor.

Additionally, i've deactivated all plugins to see what will happen, but this also had no effect on the editor.
My guess is that the settings still remain in the database.

Is there any workaround or even a fix for that?

**Comment by azaozz** [comment]
> My guess is that the settings still remain in the database.

Classic Editor plugin doesn't put anything in the DB that may cause this. Seems there may be a "hack" that disables the block editor that somebody added to functions.php in the theme?
