### ISSUE TITLE
new post page still loading!

### ISSUE THREAD

**Issue by arunpc4u** [WordPress/classic-editor#195]
in the recent update 1.6.3, i'm facing problem on create new post! problem is https://example.com/wp-admin/post-new.php is not 
 finishing loading it loads until the page should not crashed!

please fix this asap
Thank you so much for this amazing plugin! ♥

**Comment by FlyXam** [comment]
This post need more attention... I am facing the same problem. 
On my site, the problem is the "All in one SEO" plugin. Deactivating the pro or using the free version of AIO SEO fixed it.

**Comment by azaozz** [comment]
Sounds like this was a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

**Comment by arunpc4u** [comment]
actually, this problem was created because of AIO SEO Plugin update that release that time, but after few day it was fixed that time! so now there is no issue like this!
