### ISSUE TITLE
Adjustable editor width/size

### ISSUE THREAD

**Issue by trance23** [WordPress/classic-editor#196]
Hey there. Thanks every for the work on this plugin.

Just wanted to share a minor tweak that I find useful, as I don't like editing in a widescreen editor, and find it easier to have a narrower editing field. I installed the Admin CSS MU to be able to do this. Perhaps it can be added as an option in the plugin?

Thanks.

 `#poststuff {
	min-width: 0;
	width: 960px;
	margin: 0 auto;
}`

**Comment by azaozz** [comment]
Yep, there are several ways to implement this in CSS. Thanks.
