### ISSUE TITLE
Editor converts <br> to &nbsp; when switching from Text editing to Visual editing

### ISSUE THREAD

**Issue by BruteForceOAP** [WordPress/classic-editor#199]
This is a real pain. I use <br> to space to introduce a newline. If I just use enter in the Visual editor this is ignored when I save the post. &nbsp; results in 2 empty line instead of 1.

So, in the Text edit, I type this (I use [ ] instead of "less Than", "more than" characters as they are interpreted as code):

[div]This is line 1[/div]
[div]this is line 2[/div]

which results in:

This is line 1
this is line 2

Okay, so now I need an empty line between them:

[div]This is line 1[/div]
[br][div]this is line 2[/div]

This gives me:

This is line 1

this is line 2

**Which is what I want.**

But if I then switch Visual and back to text I see this:

[div]This is line 1[/div]
&nbsp;
[div]this is line 2[/div]

Which, gives this:

This is line 1

this is line 2

If I use [div][/div] it shows in Visual as a single empty line, but in the website as NO empty lines.

How do I stop this from happening or get the result I want?

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
