### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by pento** [WordPress/classic-editor#2]
We need to remove the beta warning, and update the "tested up to" to 4.9.8.

**Comment by pento** [comment]
Actually, the "tested up to" doesn't need to be changed.

The text could do with some work, though.

**Comment by pento** [comment]
Beta warning is gone as of 0.4, leaving this open to remind myself to check the rest of the text.

**Comment by azaozz** [comment]
> leaving this open to remind myself to check the rest of the text

Yep, lets use this for updating the readme before the v.1.0 release.

**Comment by azaozz** [comment]
Done in https://github.com/WordPress/classic-editor/commit/9f20053a5ef7c2c50fce99fba2594444b16966fb.
