### ISSUE TITLE
Editing Slug to an Existing Slug causes wrong content to display

### ISSUE THREAD

**Issue by Ipstenu** [WordPress/classic-editor#201]
I am aware this is a weird one.

The setup is as follows:

1. Make a clean website
2. Make a couple posts (content does not matter) 
3. Install and Activate Classic Editor
4. Make a new post and save as draft
5. **Copy** the permalink from an existing post and paste it into the new post as the permalink, save as DRAFT (do not publish)
6. You will see the NEW post has a `-2` added to the permalink
7. Open the existing post with the non `-2`

The post will display the content (title and all!) from the NEW post that is _still in draft_

This does not happen with the Block Editor.

I dug up that this is **fixed** in Gutenberg per https://core.trac.wordpress.org/ticket/52422 however it still exists in classic editor.

I reproduced this on WP 4.9.22 as well.

**Comment by joedolson** [comment]
If you reproduced this in 4.9.22, I assume that was without the classic editor plug-in? If so, this seems like it's probably a core bug, rather than a classic editor plugin bug.

**Comment by Ipstenu** [comment]
@joedolson That's why I linked to the trac ticket where it _appears_ that this was corrected in the block editor. 

I tested on 5.9 and it _does not_ happen, which makes it look like it was fixed in core, and not accounted for whatever Classic is doing.

Would the fix belong in core (which is getting rid of classic) or the plugin that activates it?

I honestly don't know, but since in 6.2.2 the only way to reproduce it is via the Classic Editor, the it sort of argues that this should be fixed IN Classic Editor... if possible. Which I still don't know.

**Comment by joedolson** [comment]
I think that the fix belongs in core, still; none of the relevant code is in the plugin, so any fix still needs to be committed to core.

The classic editor is still automatically enabled in some cases in core, such as custom post types without REST API support.

**Comment by Ipstenu** [comment]
Alrighty then, to core it goes.

**Comment by azaozz** [comment]
> Alrighty then, to core it goes.

Thanks!!
