### ISSUE TITLE
Unable to Publish Post Using Classic Editor Plugin

### ISSUE THREAD

**Issue by latitude504** [WordPress/classic-editor#203]
I am unable to publish a post when using your Classic Editor plugin to override Gutenberg as the post editor. It was working as recently as Friday, July 28th, but when I tried to publish a post on Sunday, July 30th, it generated a “This page isn’t working” HTTP 500 error. At first, I disabled the plugins and enabled them one at a time, attempting to publish a post before enabling each plugin. The issue recurred when I enabled your plugin. I have not made any updates to the core, plugins, or the theme (Astra) in a while, nor have I installed any new plugins or themes.

Any help would be appreciated.

**Comment by azaozz** [comment]
This seems caused by another plugin. Please test with all other plugins disabled.
