### ISSUE TITLE
No Auto Save (or prevent closing tab)

### ISSUE THREAD

**Issue by BenoitAdam94** [WordPress/classic-editor#205]
Classic Editor doesn’t autosave nor prevent you when you are closing a tab that the post you are writting is not saved.

I try to install a plugin called “wp-autosave” but It doesn’t work

Any ideas ?

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
