### ISSUE TITLE
Code changes when switching to visual editor

### ISSUE THREAD

**Issue by Voodoochill** [WordPress/classic-editor#206]
(As reported here:)

https://wordpress.org/support/topic/code-changes-when-switching-to-visual-editor/

In the html text editor I add embed code:

    <figure>
    <figcaption class="audiocaption">Title</figcaption>
    <audio controls controlsList="nodownload" src="https://examples/xxx.mp3">
    </audio>
    </figure>

When switching to visual editor it strips out 

    controlsList="nodownload" . 

Although this is not yet a recognised html attribute, it is recognised by Google Chrome browser and it removes the download button which is important.

**Example 2** 
A span tag with no attributes will be removed when switching to visual editor. e.g. `<span>this is a span</span>` will lose both start and end tag. It is quite normal to use an empty span tag in CSS to separate a specific pice of text for different styling.

    <div class="Mary" >
    Mary had a <span>little lamb</span>
    </div>

CSS:
    .mary
    {color:red}
    .mary span
    (color:green}

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
