### ISSUE TITLE
Incorrect output of button <b>

### ISSUE THREAD

**Issue by BlackStar1991** [WordPress/classic-editor#207]
Is it possible to solve the problem that the b button - which gives a bold style to the text - was implemented as a <b> tag?

This is the <strong> tag and we have millions of sites in the world that use the TinyMCE editor library and are aware of this error.

*Perhaps because by default WordPress changed the tag usage rule from <b> to <strong> , the W3C guidelines no longer consider the tag to be a semantically strong tag. 
Just imagine how much space in databases you will save if, instead of the <strong> tag, when you click the "b" button, the text will be wrapped in the <b> tag... Every site that functions on WP

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
