### ISSUE TITLE
Classic editor issue with User role functionalities

### ISSUE THREAD

**Issue by niralibiniwale** [WordPress/classic-editor#208]
I've implemented the Classic Editor plugin on my website and aim to achieve the following functionality:

Upon a user creating a post, it should enter a pending review status. Once approved by the admin, that user should be able to edit the post, but any edits should again trigger a pending review status.

I've assigned the default Contributor user role for new posts, and it's functioning correctly. However, when I added the `edit_published_posts` capability to the Contributor role, editing became possible, but the post was directly updated without undergoing the desired pending review process. For a detailed demonstration of the behavior in both the Classic Editor and Gutenberg, please refer to the video linked below:

(https://drive.google.com/file/d/1DAjDLZ0059oMvM-Iz1R4fjjtNmC1aFDR/view?usp=sharing)

**Comment by azaozz** [comment]
Seems the functionality you need is outside of the scope for this plugin. A (granular) user roles plugin may be more helpful to achieve it.
