### ISSUE TITLE
Bug: Classic Editor brings back an old version of the post to edit

### ISSUE THREAD

**Issue by nivaldo9** [WordPress/classic-editor#209]
Hello.

Since this week, when I open a post to edit, the editable page shows an old version of the same post.

Disabling plugin by plugin, I find out that Classic Editor is causing this bug.

Using Gutenberg, it shows the correct version to edit.

It happened with someone else?

Can I have some help here? I didn't see this issue in another question.

Regards.

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
