### ISSUE TITLE
WYSIWYG Bug

### ISSUE THREAD

**Issue by agndesigns** [WordPress/classic-editor#210]
TinyMCE is no longer displaying "Underline" as an option within Bold / Italic.  Is this an issue with TinyMCE itself, or a bug with wp 6.4.1 + classic 1.6.3?

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
