### ISSUE TITLE
Image CAPTIONS embed a fixed Width on FIGURE output, making it unresponsive

### ISSUE THREAD

**Issue by xavierve** [WordPress/classic-editor#211]
When adding captions to an IMAGE, classic editor styles it with an fixed Width.
So FIGURE tag output (frontend) use an embeded fixed style  on pixels that makes picture non responsive
[https://wordpress.org/support/topic/image-width-style-embeded/#post-17263319](url)

Reproducing the but (i m using TT2 and TT4 themes)
On classic editor
1- clic on add MEDIA (an image)
2- select image
3- write something on LEYEND
4- ADD
5- image showed with his leyend on  visual view. In HTML  view shows
[caption id="attachment_53" align="alignnone" width="1024"]
6- view page on front-end , 
Mobile view is not responsive, so image is oversized outside the screen
in HTML (front end) FIGURE embeded style has 1024px Width.
__

So, passing CAPTION width="1024"] seams a bad idea.

I found a workaround to solve it

1- edit functions.php of yout theme
2- add following line remove the fixed WIDTH pixels
add_filter(‘img_caption_shortcode_width’, ‘__return_false’);

BUT it would  be nice if you can fix the CORE itself

thanks!

**Comment by azaozz** [comment]
Sounds like this is a problem with the (old) Edit Post screen, not with this plugin. Classic Editor plugin only enables the use of the old editor, it doesn't affect how it works.

If this has been tested with all other plugins disabled, and it seems to be an old bug on the Edit Post screen, please feel free to open a Trac ticket with the full description and how to reproduce it.
