### ISSUE TITLE
Classic Editor view in combination with ACF is broken in Safari 18.0

### ISSUE THREAD

**Issue by florian-strasser** [WordPress/classic-editor#220]
We currently don't know if this is a safari related issue or a classic editor related one. I'm not the only one experiencing that problems:

https://wordpress.org/support/topic/safari-18-0-breaking-classic-editor/

But I thought GitHub would be the better place to fix this problem. I guess it's a mix out of a safari / classic editor related problem. I guess the float:left; and float:right; mix is the problem.

<img width="1724" alt="image" src="https://github.com/user-attachments/assets/f56e550e-ca25-4aaa-8284-de9c838932b0">

The Problems could be fixed by dropping the float css and switch over to position absolute the right sidebar or switch over to a flex layout.

If necessary I can help with the necessary changes.

**Comment by azaozz** [comment]
Thanks for opening this issue. This is actually a Safari bug that affects all metaboxes, not just ACF, and eventually will be fixed in WP 6.7. It is also reported on Trac: https://core.trac.wordpress.org/ticket/62082.

Added a temp fix to the Classic Editor plugin for now: https://github.com/WordPress/classic-editor/commit/ebd9da7f389d7ab18852d49e26463a8aafa21a12. New version of Classic Editor will be released as soon as the fix is confirmed working as expected. Please test if possible :)

**Comment by ironprogrammer** [comment]
## Test Report
Thanks for the fix, @azaozz! I can confirm that this resolves the metabox float issue on macOS Sequoia with Safari 18.0. (Tested in Playground.)

### Test Instructions
1. With Classic Editor enabled, open a new or existing post.
2. In the Screen Options tab, enable Custom Fields. Alternative: enable a plugin that adds metaboxes, such as ACF.
3. 👀 Observe the display of the metaboxes.

### Actual Results
- ✅ Issue resolved with patched `classic-editor.php` (downloaded plugin repo zip and uploaded into Playground to install).

| Safari 18.0 before patch ([Playground](https://wordpress.org/plugins/classic-editor/?preview=1)) | After patch ([Playground](https://playground.wordpress.net/?blueprint-url=https://gist.githubusercontent.com/ironprogrammer/ce478ac9f2beeda5cd28e43796fbacbc/raw/158980c2b5aac5b422367b397cbf1cf225f2fdfb/blueprint.json)) |
|:-:|:-:|
| <img src="https://cldup.com/cDcurWbVuG.png"> | <img src="https://cldup.com/CqvRwcUOty-3000x3000.png"> |

**Comment by rghedin** [comment]
Added the fix by @azaozz via [Userscripts](https://github.com/quoid/userscripts) extension and worked like a charm!

<img width="1319" alt="Captura de Tela 2024-09-27 às 07 16 21" src="https://github.com/user-attachments/assets/33517206-6a6c-4367-b63c-3c2825128522">

**Comment by ironprogrammer** [comment]
Closing this as resolved with https://github.com/WordPress/classic-editor/commit/ebd9da7f389d7ab18852d49e26463a8aafa21a12, which has been [deployed to the plugin directory in version 1.6.5](https://wordpress.org/plugins/classic-editor/).
