### ISSUE TITLE
Infected sites - URGENT

### ISSUE THREAD

**Issue by mvldebian** [WordPress/classic-editor#224]
I am dealing with 4 cases of infected sites that have the Classic Editor installed in common.

The files detected by Wordfence are inside the plugin directory, and a last file is tampered with and causes the problem. The site starts redirecting the URLs to malicious and gambling sites.

Attached is a sample of one of the sites that was affected.

It must have been something on a large scale because I was contacted by NIC.br, one of the internet management organs in Brazil, and it seems that many more cases are occurring.

[AMOSTRAS-CERT-NIC.zip](https://github.com/user-attachments/files/17939800/AMOSTRAS-CERT-NIC.zip)

**Comment by azaozz** [comment]
Sorry to hear about the compromised sites. 

> The files detected by Wordfence are inside the plugin directory, and a last file is tampered with and causes the problem.

This is somewhat common when a site is compromised. Seems the culprits tried to hide infected files in the plugin's directory. They probably chose `/classic-editor` as this plugin is commonly used. 

Unfortunately the plugin cannot do anything to remedy this. Best suggestion would be to delete it on the compromised sites and then install it again. This should revert all files to their proper content and remove any extra files from the directory.

Going to close the issue but if you think there's something the plugin can do feel free to reopen it.

**Comment by mvldebian** [comment]
Good evening

I am not questioning your answer, I am just making an observation that of the many WordPress sites that I host, some of which are very outdated, the only sites that were compromised were those that had the plugin installed.

I will continue to monitor my environment and will let you know if I have any more similar incidents.

Thank you.
