### ISSUE TITLE
Switch editor meta box / sidebar panel: consider to remove l/r margins

### ISSUE THREAD

**Issue by afercia** [WordPress/classic-editor#28]
I'd suggest to remove the left and right margin from the "Switch link" in the metabox (same in the sidebar panel in Gutenberg) to have the text better aligned with other text in other boxes / panels:

<img width="320" alt="screenshot 2018-12-06 at 16 47 58" src="https://user-images.githubusercontent.com/1682452/49595598-9c642280-f978-11e8-8e35-d3d3de6afdbe.png">

See the inline style `<p style="margin: 1em;">`

**Comment by azaozz** [comment]
I'd rather add the same to the link in Featured Image metabox. Think the Editor metabox looks better, margins are more "even". (But that's just my opinion) :)

Will revisit that soon when enabling the plugin to add that to the Block Editor menu and removing the metabox there.

**Comment by azaozz** [comment]
Corrected that in https://github.com/WordPress/classic-editor/commit/354caf032e42ddfd43716be12566a2fa4b953673 (still think it doesn't look better) :)
