### ISSUE TITLE
Default to Classic Editor

### ISSUE THREAD

**Issue by pento** [WordPress/classic-editor#3]
When the Classic Editor plugin is installed and activated, the user is pretty clearly intending to opt out of Gutenberg.

The default behaviour of the Classic Editor plugin should be to opt the user out of Gutenberg, they can then opt back in on the Settings -> Writing screen.

**Comment by danielbachhuber** [comment]
This is already the case:

https://github.com/WordPress/classic-editor/blob/3cf2f364b504c962705ba2b25ae262f73646af5a/classic-editor.php#L349-L357

When I activated the Classic Editor plugin alongside Gutenberg, the Classic Editor took priority by default.

Maybe you already had the `classic-editor-replace` option set locally?

**Comment by pento** [comment]
I may've had an old version activated on the site previously: 0.2 defaulted to `no-replace`.
