### ISSUE TITLE
z-index issue with Editor and sub menus

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/classic-editor#32]
I have an issue with the editor field overlaying sub menus:

![z-index-issue](https://user-images.githubusercontent.com/2310924/49646210-ba845e00-fa1e-11e8-91d5-804bccc94e82.png)

I’m using Firefox 65.0a1 (2018-12-06) (64-Bit) on Windows 10. Adding a `z-index` of `0` to the `#wp-content-editor-container` seems to fix it.

**Comment by florianbrinkmann** [comment]
Hm, cannot reproduce it in another installation, so maybe an issue with another plugin on that specific site.

**Comment by azaozz** [comment]
Could be, I can't reproduce it either...

**Comment by florianbrinkmann** [comment]
I’ll try to find out what causes the issue and report it here, maybe that helps if someone should have the same issue :)
