### ISSUE TITLE
Filter to hide "Classic Editor" post state

### ISSUE THREAD

**Issue by timbriteweb** [WordPress/classic-editor#34]
Can you add a filter to the `add_post_state` function to not include the "Classic Editor" string on the post listings? We don't use Gutenberg and this tag had already confused one of my clients! 

Something like this at the top of the function: 
`if ( apply_filters( 'classic_editor_hide_post_state', false ) ) return $post_states;`

**Comment by azaozz** [comment]
This only shows when the user is allowed to switch editors. If you don't user Gutenberg/Block Editor, you should probably disable it, then the "Classic Editor" state will not be shown.

**Comment by azaozz** [comment]
No follow-up for a few months, assuming such filter won't be that useful. Also, the post state can be removed from a plugin easily by using existing filters in core.
