### ISSUE TITLE
"Switch to Block Editor" button not working

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [WordPress/classic-editor#39]
I am using a self-created child theme of Twenty Twelve. 

However, when I use this plugin and click "Switch to Block Editor", the page still has the classic editor on a refresh.

**Comment by azaozz** [comment]
Could you test again with version 1.2. A bug with switching editors for new posts was fixed there.

**Comment by vijayaraghavanramanan** [comment]
I can of course switch but the previous version was a bit different. 

In the editor, there was an option to change it, but it's gone. 

Now I can only change in "Settings > Writing". 

Also I can't any longer go to "All Posts" and chose to edit with the choice of editor.

**Comment by vijayaraghavanramanan** [comment]
Oops, just realized what needed to be done to bring back the behaviour of the previous version. Plus I see the bug has also been fixed. Thanks. Closing.
