### ISSUE TITLE
Add an option to open a post in Gutenberg

### ISSUE THREAD

**Issue by pento** [WordPress/classic-editor#4]
Once Classic Editor is installed and activated, it's impossible to get into Gutenberg, which prevents people from trying it out.

Having a subtle option for this would be useful.

**Comment by karmatosed** [comment]
I think many want it to be impossible, so this is maybe ok? If some people are installing as a network option they'd want this.

**Comment by pento** [comment]
That's fair, maybe Ramp is the better option for folks who want to be able to default to Classic, but try out Gutenberg occasionally, as they implement support.
