### ISSUE TITLE
Selecting text on mobile with Classic Editor won't work

### ISSUE THREAD

**Issue by wetterwebdesign** [WordPress/classic-editor#44]
While on a mobile device using the visual mode and editing a post, I was attempting to select a paragraph of text to cut and paste it in another area of my post. However, when you go to select the text by dragging the ending cursor the selection jumps way down on the content area.

The only way around this currently is to switch to Text mode, which is not ideal for the typical user.

**Comment by luciano-croce** [comment]
What have to do with the "Classic Editor" plugin? :smile:

**Comment by wetterwebdesign** [comment]
Well, if the user can select their text in text mode of the classic editor
on mobile...

And they can’t select their text in visual mode of the classic editor on
mobile...

That would seem to be a problem with the classic editor in visual mode.
Correct?

**Comment by luciano-croce** [comment]
@wetterwebdesign wait that also @azaozz read this...
