### ISSUE TITLE
When Gutenberg is not active, the "Classic editor settings" should not show

### ISSUE THREAD

**Issue by pbiron** [WordPress/classic-editor#5]
If Classic Editor is active but Gutenberg is not I think the "Classic editor settings" are potentially confusing to users.

For example, if the user selects "Use the Gutenberg editor by default and include optional links back to the Classic editor." when Gutenberg is not active the user still gets the classic editor and may wonder why.

The fix is easy and I can do a PR if needed.

**Comment by pento** [comment]
Folks will still want to preselect the option before WordPress 5.0: perhaps an explanation with the setting would be helpful in this case.

**Comment by pbiron** [comment]
Sure, that would work for me.

How about something like:

![class-editor-settings-explanation](https://user-images.githubusercontent.com/3824560/43231863-6529653e-902b-11e8-8de7-050766928ef1.png)

I'm more than open to suggestions for wordsmithing the explanation.

**Comment by aaronjorbin** [comment]
I think the explanation can be dependent upon the current state of gutenberg. Maybe something like:

`Note: Gutenberg is not currently installed. The classic editor will remain the only option until it is available`

**Comment by pbiron** [comment]
Do you mean that the explanation would only be displayed when Gutenberg is not active?  If so I agree.

Here's a minor tweak to your wording:

`Note: the Gutenberg editor is not currently activated. The Classic editor will remain the only option until the Gutenberg editor is available`

**Comment by azaozz** [comment]
Been thinking about the text there and about supported WP versions. 

As core refers to the new editor as "Block Editor", this plugin should do the same. However imho we should keep the `Requires at least: 4.9` header, as it supports to be installed on WP 4.9 before upgrading to 5.0.

Should any help text(s) be adjusted depending on the WP version? I'm assuming Classic Editor will be installed immediately prior to upgrading WordPress, or right after (by people that will find out about it from the post-install screen).

**Comment by pbiron** [comment]
> Should any help text(s) be adjusted depending on the WP version?

I think that would be good idea.  If the site is 4.9 + GB Plugin refer to it as `Gutenberg`; if the site is 5.0+, refer to it as `the block editor`.

**Comment by luciano-croce** [comment]
I think the exact the opposite: it would be necessary to unify the terms, in order not to create confusion, and have more consistency in two core branches 4.9+ and 5.0+

Gutenberg    ->   Block Editor -> 4.9+ and 5.0+ (with or without Gutenberg installed).
editor classic -> Classic Editor -> 4.9+ and 5.0+ (with or without Gutenberg installed).

I think that the Gutenberg Editor plugin should also go in this direction.... (IMHO).

Other core directions in 4.9+ for better understanding (IMHO):

Visual Editor
Code Editor

**Comment by azaozz** [comment]
Yeah, it can get confusing. There are two editors now:

New editor - Gutenberg = Block Editor in 5.0
Old editor - TinyMCE - Visual Editor = Classic Editor in 5.0

In addition there is a "Classic Block" in the new editor, and we used to refer to Visual and Text editors in the old editor.

Not sure if we can change any of this now :)
