### ISSUE TITLE
PHP Notice: edit_form_advanced deprecated in 5.0

### ISSUE THREAD

**Issue by luciano-croce** [WordPress/classic-editor#54]
PHP Notice: edit_form_advanced deprecated in 5.0 use block_editor_meta_box_hidden_fields

DEPRECATED -> remove_action( 'edit_form_advanced', 'gutenberg_intercept_meta_box_render' ); 
REPLACE -> remove_action( 'block_editor_meta_box_hidden_fields', 'gutenberg_intercept_meta_box_render' );

**Comment by azaozz** [comment]
A `remove_action()` shouldn't trigger that warning. It just tries to remove something that's not there and fails silently :)

I don't see it happening here but will try to reproduce and add a fix in core.

**Comment by luciano-croce** [comment]
@azaozz if you enable debug and debug log in config.php you you find it ;)

**Comment by azaozz** [comment]
Nope, not seeing it here :)

BTW it seems it should show with `define( 'WP_DEBUG_DISPLAY', true );` too. If you're still seeing it, maybe there is another plugin that uses the `edit_form_advanced` filter?

**Comment by luciano-croce** [comment]
> If you're still seeing it, maybe there is another plugin that uses the edit_form_advanced filter?

No.

**Comment by luciano-croce** [comment]
"NO" as in there aren't other plugins enabled...

**Comment by azaozz** [comment]
Hmm, no follow-up for a few months, assuming this has been resolved. Still, would have been good to get to the bottom if it...
