### ISSUE TITLE
Classic Editor 'Visual' tab not available

### ISSUE THREAD

**Issue by anadearmasnet** [WordPress/classic-editor#59]
Hi everyone, even though this classic editor looks awesome, I cannot seem to have the 'visual' and 'editor' tabs available while trying to add a post. Everything else is correct and as the classic editor was, but the two tabs, 'visual' and 'editor' aren't available. The post is automatically shown as 'editor' (code) and doesn't allow me to change it to 'visual'. Any help?

**Comment by azaozz** [comment]
Have you checked the "Disable the visual editor..." checkbox on your profile by mistake?

If not, perhaps look for js errors in the browser tools and post to the support forum: https://wordpress.org/support/plugin/classic-editor.

**Comment by anadearmasnet** [comment]
Hi @azaozz! You're right! I somehow disabled the visual editor! Thank you so much for your help!
