### ISSUE TITLE
Hide Gutenberg endpoints in REST API

### ISSUE THREAD

**Issue by rmens** [WordPress/classic-editor#65]
Hey guys,

Thanks for saving my butt with this plug-in! I was wondering if it's possible to disable all the Gutenberg endpoint in de REST API. For example:

```wp/v2/blocks```
```wp/v2/types/wp_block```
```wp/v2/block-renderer/```

They clutter things up when the default editor for all users is the classic editor and users can not switch to the block editor.

**Comment by azaozz** [comment]
No follow-up for a few months, assuming there isn't much interest in disabling parts of the REST API. Also, may not be the best idea, could introduce unexpected bugs, etc. :)
