### ISSUE TITLE
With Yandex Metrica, It Is Not Woking

### ISSUE THREAD

**Issue by alpintomtom** [WordPress/classic-editor#66]
Hi there,

I really like to use classic WP Editor plugin. But Now I realized that, the time I use this plugin, my yandex metrica plugin started not to work , It does not send the data. When I deactiveted it(Classic Editor Plugn), yandex metrica counter started to work again, I think it has some problems. You may wanna check it.
PS: I am also using Google analytics and its plugin as well.

Thank you.

**Comment by azaozz** [comment]
The Classic Editor plugin only enables the classic editor, it doesn't change how it works. Perhaps the plugin that stopped working was updated and now doesn't work with the classic (old) editor any more in WP 5.0? I'd suggest asking the plugin author.

**Comment by azaozz** [comment]
No follow-up for a few months, assuming the problem has been resolved.
