### ISSUE TITLE
YOAST Page description not working

### ISSUE THREAD

**Issue by josefprado** [WordPress/classic-editor#67]
When we use YOAST, just after the article we are able to edit whats will be the description the page will show to the search engines.

This used to work fine in the classic editor before Guttemberg. Now, even using the Classic Editor Plugin (that saved us from Guttemberg) this fields that woudl allow us to edit the description are missing. We can see the YOAST space there, but its blank.

**Comment by azaozz** [comment]
Think this was fixed already in Yoast. If not, perhaps reverting to an older version would help until it is fixed.
