### ISSUE TITLE
Pasting YouTube URLs breaks edition

### ISSUE THREAD

**Issue by josefprado** [WordPress/classic-editor#68]
When I do paste a YouTube URL in a paragraph, the youtube URL disappears, code editor stops working (when you click, notting happens), and after you save, you lost everything.

Please, PLEASE, PLEASE, just make sure the classic editor plugin is 100% compatible with everything we are used to have, or just remove Guttemberg from core, let it as a Plug-in, and whoever wants to use it, download it.

Guttemberg is breaking our websites and making the post editing a pain...

**Comment by azaozz** [comment]
Don't think pasting of URLs in the editor has anything to do with this plugin. It only enables the previous/classic editor, it doesn't change how it works.

Check for any JS errors in the console that may give clues about what's going on.
