### ISSUE TITLE
Copy & Paste from Word with Formatting removes spaces

### ISSUE THREAD

**Issue by CardozoLRev** [WordPress/classic-editor#69]
When creating news posts using the Classic Editor plugin in Wordpress v. 5.03, copying and pasting from Microsoft Word with formatting (something necessary for the types of posts I am creating), results in spaces between words being randomly removed from the text.  It appears to be related mostly to words coming after italicizes words.  For example, the phrase "_See_ discussion _supra_ note" would appear "_See_discussion_supra_note" with no spaces between.

**Comment by azaozz** [comment]
Same as in https://github.com/WordPress/classic-editor/issues/66. This plugin only enables the classic editor, it doesn't change how it works. Perhaps check for any JS errors and/or any other plugins that may be changing how pasting in the Classic Editor works..
