### ISSUE TITLE
Wrong link on About page in multisite network dashboard

### ISSUE THREAD

**Issue by patriciabt** [WordPress/classic-editor#70]
Seen on a client's multisite, with the classic editor plugin, set up to allow all sub-sites admins to choose to be able to switch editors.

When I updated from 5.0.2 to 5.0.3, and landed on the About page, I got this message (that appears only when on About page)

_"The Classic Editor plugin prevents use of the new Block Editor. Change the Classic Editor settings."_

"Change the Classic Editor settings" ... is a link to /wp-admin/network/options-writing.php#classic-editor-options which leads to a 404 as the options-writing is only available at sub-site dashboard, not on the network admin. When removing the /network/ part of the links, landed in the correct setting for the main site. 

I guess that link is hardcoded somewhere, valid for standalone installs only.

Thx

![image](https://user-images.githubusercontent.com/1843660/51041744-e74a0900-15ba-11e9-9b9e-9624478b7503.png)

links to:
![image](https://user-images.githubusercontent.com/1843660/51041774-fd57c980-15ba-11e9-9667-db55dfa6c00d.png)

**Comment by azaozz** [comment]
Right, that's a bug. Will fix in the next release. Thanks :)

**Comment by patriciabt** [comment]
Great. Thx.
