### ISSUE TITLE
Visual Editor for Classic Editor Plugin with 5.0.3 does not support embeds

### ISSUE THREAD

**Issue by akaufman3** [WordPress/classic-editor#72]
Copying and pasting in embeds such as Instagram and Youtube throws the below error even with all other plugins deactivated.
**These are the two urls I am testing:**
https://www.youtube.com/watch?v=G8KpPw303PY 
https://www.instagram.com/p/Bsbgc7tjCJv/

**Error:**
<img width="1235" alt="screen shot 2019-01-17 at 10 19 51 am" src="https://user-images.githubusercontent.com/4086943/51328989-88651380-1a42-11e9-9aeb-ce36510569ea.png">

**This is the generated code I am seeing after switching back from Visual tab to Text tab:**
```<span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start"><span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start">﻿</span><span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start">﻿</span>﻿</span>https://www.instagram.com/p/Bsbgc7tjCJv/```

```https://www.youtube.com/watch?v=G8KpPw303PY <span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start">﻿</span>```

Has anyone else come across this issue?

**Comment by azaozz** [comment]
This usually means that --something-- is trying to load Gutenberg/Block Editor's scripts while the Classic Editor is being used. Perhaps your theme is doing that?

The `<span data-mce-type="bookmark"...` are internal markings for TinyMCE. They are removed before saving but are visible here as there was a JS error preventing their removal.

**Comment by arlg** [comment]
Hi, I would like to add that I've got the same problem on many sites. The <iframe> tag is removed when I save my post. No debugging errors, the iframe is just wiped out before database save.

Wordpress V 5.0.3
Classic Editor V1.4

**Comment by azaozz** [comment]
No follow-up for a few months, assuming this has been resolved, one way or the other. If there are still problems with removed HTML when saving, perhaps post on the support forum where more people will be able to help https://wordpress.org/support/plugin/classic-editor/.
