### ISSUE TITLE
Glitch 

### ISSUE THREAD

**Issue by fqvqvf** [WordPress/classic-editor#73]
There seems to be an editing problem that I believe is because of Classic Editor. I can't change the custom headers anymore ever since I updated to 5.0.3. Every time I click the red button to remove the photo, the box below opens up. 

Help!!

![1](https://user-images.githubusercontent.com/46825964/51407486-094b0a80-1b2a-11e9-8f79-144a44178ca6.jpg)
![2](https://user-images.githubusercontent.com/46825964/51407493-0cde9180-1b2a-11e9-8da3-b3123165d420.jpg)

**Comment by azaozz** [comment]
Where is this screen from? :) Perhaps look on their site for an updated version or contact the author.

**Comment by azaozz** [comment]
No follow-up for a few months, assuming the problem has been resolved.
