### ISSUE TITLE
Enabling the plugin Kill the RSS Feed

### ISSUE THREAD

**Issue by teklayde** [WordPress/classic-editor#75]
Enabling this plugin, kills my RSS feed. All plugins enabled except this one (Classic-Editor), and my feed works great!

**Comment by azaozz** [comment]
Hm, tested on several sites and RSS works properly on all. This plugin doesn't really do anything on the front-end, don't see how it can affect the feed.

**Comment by azaozz** [comment]
No follow-up for a few months, assuming the problem has been resolved.
