### ISSUE TITLE
Classic Editor Strips Gutenberg Image Block

### ISSUE THREAD

**Issue by sc456a** [WordPress/classic-editor#76]
If you flip back and forth between Visual/Text editing in Classic Editor a few times it'll strip the Gutenberg image block code. [See here](https://www.youtube.com/watch?v=F_lZY2piRXQ).

**Comment by azaozz** [comment]
Generally it is not a good idea to switch editors. That's why the Classic Editor plugin "remembers" the last editor used for each post.

If you want to have the classic editor functionality inside the Block Editor, perhaps look for a plugin that adds it there :)

**Comment by sc456a** [comment]
This is like going to the doctor and telling her that your arm hurts when you lift it and she just tells you not to lift it.
