### ISSUE TITLE
About "network true" removed

### ISSUE THREAD

**Issue by luciano-croce** [WordPress/classic-editor#79]
Recently "Network: true" was removed from plugin header.

- When in a Network Multisite exist more Admin's and all Admin's mange a site individually, but, in a Enterprise Environment's this is no good well.

- When in a "Network Multisite" a Super Admin "Network Activate" Classic Editor and a Admin standalone activate Classic Editor in your site, the network settings overwrite all other settings of single sites.

This is the problem!

Solution?

Add a option for Super Admin's (in Classic Editor plugin) to "allow" or "not allow" Network: true settings (false by default) indipendently if it break some functionality.

Francly when I Super Admin of my Network Multisite I dont'allow the other Admin's to install Themes or Plugins "separately-individually" in sites.

This is just my idea, written to encourage discussion with other users and get other opinions.

Another aspect is: without "Network: true" the plugin is not "really" Network Multisite compliant.

**Comment by azaozz** [comment]
> in a Enterprise Environment's this is no good...
> ...
> Add a option for Super Admin's (in Classic Editor plugin) to "allow" or "not allow" Network: true settings (false by default) indipendently

This already exists (by default) in WP. It is a checkbox to allow site admins to manage plugins. When unchecked (the default) site admins cannot manage plugins regardless if they are `Network: true` or not.

In cases where the plugin is not network activated and the `Enable administration menus   [ ] Plugins` checkbox in unchecked (i.e. site admins cannot manage plugins), a network admin will have to log-in on each site and manage the plugins. That's how it works for all plugins and don't think we should change it :)

**Comment by luciano-croce** [comment]
Sorry for delay... Absolutely TRUE!

I did not remember this native multisite option.

In this sense ,of fact, it is useless.
