### ISSUE TITLE
Removing incorrect filter for `gutenberg_remove_wpcom_markdown_support`

### ISSUE THREAD

**Issue by brandonpayton** [WordPress/classic-editor#8]
I'm not sure if this belongs in the Classic Editor plugin because it is WP.com-related, but I'm filing this because exists here for now.

This plugin attempt to remove `gutenberg_remove_wpcom_markdown_support` using a now-incorrect filter name and priority.

Instead of "rest_pre_insert_post" and the default priority, the current filter uses "wp_insert_post_data" and priority 9. The latest can be checked [here](https://github.com/WordPress/gutenberg/blob/master/lib/plugin-compat.php#L34).

Thanks!

**Comment by azaozz** [comment]
Thanks! Fixes in https://github.com/WordPress/classic-editor/commit/bbb597f92ad6a4c9c1e69f88a2a17f1ebd26ef1c.
