### ISSUE TITLE
Error in declared Stable Tag on WordPess.org Repository

### ISSUE THREAD

**Issue by luciano-croce** [WordPress/classic-editor#80]
Wrong declaration in Stable Tag on WordPress.org Repository:

Source: classic-editor / tags / 1.4 / readme.txt

Stable tag: declared 1.3 instead 1.4

Refer to this link https://plugins.trac.wordpress.org/browser/classic-editor/tags/1.4/readme.txt

**Comment by azaozz** [comment]
Yeah, this is a known "oddity" when working with `svn`. You are generally not supposed to change `tags`, just `branches` and `trunk`. But to release a new version you have to have a tag of it first, preferably, and then "point" the release to that tag by changing the `Stable tag` header in the readme. That ends up with an old `Stable tag` in the svn tag... Nothing to worry about, that Stable tag is only for managing releases.
