### ISSUE TITLE
Classic Editor plugin not listed on plugins page in langauges other than English

### ISSUE THREAD

**Issue by siccovansas** [WordPress/classic-editor#81]
The Classic Editor plugin isn't listed on each plugin page of all my sites in a network installation of WordPress. Looking closer at the issue it seems that it is only listed when my User language is English. The plugin isn't listed when my User language is Dutch.

**Comment by azaozz** [comment]
Hmmm, this seems like a (temporary) problem with the plugins repository. Going to https://nl.wordpress.org/plugins/classic-editor/ works properly now, and this plugin is listed in the "Uitgelichte plugins" section there: https://nl.wordpress.org/plugins/.

**Comment by siccovansas** [comment]
@azaozz I'm not sure of we are talking about the same issue. I took another look at it and found out that I was mistaken :)

I couldn't find the plugin in the Dutch version of the Plugins page in the admin section of my website because the name of the plugin 'Classic Editor' is actually translated to Dutch as well and is then called 'Klassieke editor'. None of my other plugins have translated names, so I didn't expect this :)
