### ISSUE TITLE
Posts created in Classic Editor have 'Block Editor' post state

### ISSUE THREAD

**Issue by noisysocks** [WordPress/classic-editor#82]
**Steps to reproduce:** 

1. Install the Classic Editor plugin
1. Go to _Settings > Writing_
1. Set _Default editor for all users_ to _Classic Editor_ and _Allow users to switch editors_ to _No_
1. Click _Save Changes_
1. Go to _Posts > Add New_. The Classic Editor should appear
1. Give it a title (e.g. 'Lorem Ipsum'), some content, and click _Publish_
1. Go to _Settings > Writing_
1. Set _Default editor for all users_ to _Block Editor_ and _Allow users to switch editors_ to _Yes_
1. Go to _Posts > All Posts_

**Expected result:**

The post we created should display as _Lorem Ipsum — Classic Editor_ because it was created/last opened using the Classic Editor.

**Actual result:**

The post displays as _Lorem Ipsum — Block Editor_.

**Possible solution:**

It looks like there is no `classic-editor-remember` post meta set and so we default to our _Default editor for all users_ selection. A better default, I think, would be to use [`has_blocks`](https://developer.wordpress.org/reference/functions/has_blocks/) to determine which editor the post was created with.

**Comment by azaozz** [comment]
Yes, I agree the "post state" is (somewhat) confusing. It's meant to show which editor will be used to open the post by default when clicking on the post title in the list table (so the user can pick the other editor if needed). It's not an actual "state" of the post.

> ...there is no classic-editor-remember post meta set and so we default to our Default editor for all users selection

Right, that behaviour comes from the "default editor" setting. If the block editor is used by default, then all older posts will still be opened in it regardless if they have blocks or not. This is the "standard" behaviour when this plugin is not installed. Wondering if it would be worth it to try to make that clearer, perhaps by adding "Opens in ..... editor" to the state?

Arguably we should extend the "open each post in the last editor used to edit it" and look if there are blocks in post_content when there's no meta. That would be a somewhat large change to how the plugin works at the moment, but seems the most logical thing to do. 

Another option I've tried is to have a checkbox (well, another checkbox...) that will change the behaviour and open posts without blocks and without `classic-editor-remember` meta in classic. I'd rather not add another checkbox if possible :)

**Comment by azaozz** [comment]
Should be fixed in https://github.com/WordPress/classic-editor/commit/898e3ce18d4faa74257ca06e5ae0c9aa50fd8353. That will be in the next version, 1.5, coming out in few days.
