### ISSUE TITLE
Error when activated and working in post

### ISSUE THREAD

**Issue by dwakema1** [WordPress/classic-editor#83]
Hello,

I get the following error when I activate this plugin.

Failed to load plugin: wpeditimage from url https://davidwakeman.com/wp-includes/js/tinymce/plugins/wpeditimage/plugin.min.js

Please advise.

Thank you,

**Comment by azaozz** [comment]
Please see https://wordpress.org/support/topic/common-classic-editor-errors-and-how-to-fix-them/.
