### ISSUE TITLE
Custom Post Type content not visible in Classic Editor

### ISSUE THREAD

**Issue by WilbertBongers** [WordPress/classic-editor#86]
Since the update to 5.0.3 and  Gutenberg my custom made theme does not display the content which is used in 2 Custom Post Types anymore. I installed Classic Editor plugin but the problem remains. Screenshots provided show that the content is there but not visible.
![lesmateriaal editor](https://user-images.githubusercontent.com/28860931/53087062-9527cc00-3506-11e9-8cc8-5b530efe69ed.png)
![lesmateriaal html code](https://user-images.githubusercontent.com/28860931/53087064-9527cc00-3506-11e9-98ac-c34a8d0762e0.PNG)
![lesmateriaal preview](https://user-images.githubusercontent.com/28860931/53087065-95c06280-3506-11e9-94dc-f8ef608192c0.png)

**Comment by azaozz** [comment]
Don't think this has anything to do with the Classic Editor plugin.

Looking at the first screenshot, there is a JS error on the page. Perhaps you have figured that already, but next step would be to see where that error comes from and ask for support/fix.
