### ISSUE TITLE
Ignoring image size

### ISSUE THREAD

**Issue by jimf29605** [WordPress/classic-editor#88]
I am using WP 5.1 with the Dandelion Theme. I have always used the classic editor. After a recent update of WP and Dandelion, the classic editor seems to be ignoring image size modifications such as width="900" height="600". I usually edit in Text mode, but if I select the Visual mode, all looks as I expect. After Updating the post, all of the images seem to be limited to a 600 pixel width - even if I attempt to post multiple images per row. My workspace on the blog is 1000 pixels.
 
Here is a code line that is not working:
img src="https://c2.staticflickr.com/8/7893/47212995481_14f6cbaee7_b.jpg" alt="Dimpled Trout Lily" width="900" height="600" /
 
Even older posts with image size modifications are now being displayed incorrectly.

My blog URL is www.jfowlerphotography.com
 
Note: I am using several widgets (Calendar, Recent Posts, Recent Comments) which take up about 400 pixels in a sidebar on the right side of the post. Could this be part of the problem?

Thanks in advance for any help,     Jim

**Comment by azaozz** [comment]
Don't think this is related to the Classic Editor plugin. Please start a new thread on the [support forum](https://wordpress.org/support/forum/how-to-and-troubleshooting/), seems that may be caused by another plugin.

**Comment by jimf29605** [comment]
Actually, it turned out to be a problem with the Dandelion theme. After discussing it with the theme support team, I ended up going back to an earlier version, and that solved the problem. Thanks for your response. —Jim
