### ISSUE TITLE
White text and no buttons

### ISSUE THREAD

**Issue by burningthumb** [WordPress/classic-editor#90]
I have a strange error.  There are no buttons on the classic editor and the text is white.

I get these errors on the java console:
SyntaxError: '' string literal contains an unescaped line break      wp-tinymce.js:3:317149
ReferenceError: tinymce is not defined      post.php:4635:1
ReferenceError: tinyMCE is not defined      wp-langs-en.js:235:2
ReferenceError: tinymce is not defined       post.php:4630:37

Anyone have any ideas?

Also if I switch to Gutenberg I get just a blank white screen.

So I'm left with no visual editor...

**Comment by burningthumb** [comment]
In case it helps, if I disable the Classic Editor, and have Gutenberg installed and Active I get this:
SyntaxError: "" string literal contains an unescaped line break index.js:2:75300
TypeError: wp.blocks is undefined post.php:425:1
    <anonymous> http://mireth.com/wp-admin/post.php?post=177&action=edit:425
TypeError: c is undefined index.js:50:128945
TypeError: Object(...) is not a function index.js:12:9240
TypeError: _wp$blocks is undefined editor.blocks.js:28:5
TypeError: N is undefined classic-paragraph.js:1:29049
TypeError: f is undefined wp-seo-structured-data-blocks-970.min.js:1:31756
SyntaxError: '' string literal contains an unescaped line break wp-tinymce.js:3:317149
ReferenceError: tinymce is not defined post.php:4128:1
TypeError: c is undefined index.js:50:48452
TypeError: s is undefined index.js:12:69825

**Comment by Carolkn** [comment]
Any solution to this? I have the same problem. Replacing tinymce doesn't fix it.

**Comment by burningthumb** [comment]
I used the plugin **WP Downgrade** to roll back to Wordpress 5.0.3 and that works fine.  I also raised a bug report against the wordpress core, which maybe you can add a comment on to try and gets its priority bumped up:

https://core.trac.wordpress.org/ticket/46442

**Comment by Carolkn** [comment]
I am thinking this is hosting related. The problem site is on ATT. We have multiple other sites on A2, Siteground, Hostgator with same theme & plugins without this problem, all upgraded fine. I have replaced entire core of WP, and we've done all the other suggested fixes. I have not yet tried to back out to WP 5.0.3.

**Comment by burningthumb** [comment]
In my bug report on the wordpress core I mention its only one of the sites that I manage on one of the hosting companies.  But the hosting company's support is less than useless. Having said that, if v5.0.3 works (which it does) and v5.1 does not work (which it does not) the wordpress core developer should be able to fix whatever they did between those 2 releases.

**Comment by Carolkn** [comment]
Thanks - I submitted a comment on your bug report.

**Comment by azaozz** [comment]
Thinking @Carolkn is right. This seems like a hosting problem or possibly a browser plugin/extension problem. "Something" is modifying these JS files before they reach the browser.

As this is not related to the development of the Classic Editor plugin, lets move the conversation to the support forum: https://wordpress.org/support/forum/how-to-and-troubleshooting/ :)

**Comment by bblack19438** [comment]
I have the same problem but the WP Downgrade plug-in doesn't seem to work for me.  First it tells me that version 5.0.3 is not found, and if I use core update it tells me the installation failed.

**Comment by Carolkn** [comment]
@bblack19438 : the solution that worked for some of us was to turn off pixel tracking at our host as documented in this closed ticket: https://core.trac.wordpress.org/ticket/46442
