### ISSUE TITLE
"preview" conflict with PHP 7.2 and classic-editor

### ISSUE THREAD

**Issue by unfiltered01** [WordPress/classic-editor#91]
When running classic editor in PHP 7.0 editing and "previewing" a page -- not a post -- but a page -- works. 

When running classic editor in PHP 7.2 previewing a page -- not a post -- does not work, but "publishing" does still work. 

We noticed this as we were changing hosting providers and our old provider ran PHP 7.0 but WPEngine runs PHP 7.2. The tech at WPEngine loaded 7.0 and 7.2 on my staging environment and confirmed that classic editor + "preview" worked in 7.0 and that "preview" would work in 7.2 if we turned classic editor off.

**Comment by azaozz** [comment]
This sounds like a possible conflict with another plugin that doesn't expect the classic editor to be used. Very hard to figure out without additional info. Perhaps there is "something" in the server logs? 

In any case, re-testing Classic Editor on all latest PHP versions and it seems to work as expected. If the problems continue, please try running without plugins and with a default theme, and then post to the support forum: https://wordpress.org/support/plugin/classic-editor/.
