### ISSUE TITLE
Can not switch to HTML mode in Classic Editor

### ISSUE THREAD

**Issue by theincogtion** [WordPress/classic-editor#92]
Switching between Visual mode and HTML (Text) mode is not possible in Version 1.4
![grafik](https://user-images.githubusercontent.com/10852327/55785395-a32fad00-5ab2-11e9-8451-af3db3933d38.png)

I can click on "text" but nothing happens. It stays in visual mode.

**Comment by azaozz** [comment]
Sounds like a JS error. Please look in the browser tools and copy/paste any JS errors you see to the support forum: https://wordpress.org/support/plugin/classic-editor/.
