### ISSUE TITLE
Add post state array key

### ISSUE THREAD

**Issue by CaerCam** [WordPress/classic-editor#93]
The plugin adds its own post state by appending it to the exising post states array, without any key to allow later filtering.

[This line](https://github.com/WordPress/classic-editor/blob/master/classic-editor.php#L898):
`(array) $post_states[] = $state;`
Should be something like:
`(array) $post_states['classic_editor'] = $state;`

**Comment by azaozz** [comment]
Sure. Fixed in https://github.com/WordPress/classic-editor/commit/960b63e7336dfd54570e6ec9a4db33a83d4aaac1.
