### ISSUE TITLE
Won't stop changing to visual editing

### ISSUE THREAD

**Issue by kazazzle** [WordPress/classic-editor#94]
I use this on several sites but on the most recent, the editor will not stop switching to the Visual editor. I need to use the Text option. Even when I switch to Text, it seems to save as though I'm working with the Visual option which often messes up any divs or other code I've added to the html.

Not sure why this only happens on the most recent site I've installed it on. I am working with a child theme but it's very similar to the other sites where I use it. Any thoughts on what might cause this?

https://www.reesecorgi.com

**Comment by azaozz** [comment]
Most likely there is a plugin that resets or overrides this. Likely one that is using TinyMCE somewhere else. Next step would be to try to pinpoint which one is doing it, and see if there is an option to stoop it.

In any case, this doesn't seem related to the Classic Editor plugin (I'm assuming choosing which editor to use works properly).
