### ISSUE TITLE
Remove notice after upgrade

### ISSUE THREAD

**Issue by jchristopher** [WordPress/classic-editor#95]
I'd like to suggest removing the _The Classic Editor plugin prevents use of the new Block Editor._ notice after upgrades.

I feel it adds confusion in situations where the person updating the site may be a client of a developer who has built the site and intentionally installed this plugin to prevent confusion for their client.

I understand that this plugin was originally built to be a bridge to eventually transition into using the Block Editor, but this notice after upgrades (in my opinion) is counter intuitive.

The sole purpose someone would use this plugin would be to use the Classic Editor, not the Block Editor.

Edit: Added PR: https://github.com/WordPress/classic-editor/pull/96

**Comment by azaozz** [comment]
Yes, it's probably time to remove that notice. It was intended to reduce confusion when upgrading to WP 5.0, having the plugin installed (with the default settings), and expecting to see the new editor.

As we are couple of releases past 5.0, the above case where the users may get more confused by seeing that warning seems more common. As the users are admins (have the capability to upgrade WP), they will still be able to see and change the options on the Settings => Writing screen.

**Comment by jchristopher** [comment]
Thank you @azaozz!
