### ISSUE TITLE
Text without line breaks after copying in the visual editor

### ISSUE THREAD

**Issue by Wordpress-User** [WordPress/classic-editor#97]
Text without line breaks after copying in the visual editor
Screen 1
https://core.trac.wordpress.org/raw-attachment/ticket/46403/1.jpg
Screen 2
https://core.trac.wordpress.org/raw-attachment/ticket/46403/2.jpg

**Comment by azaozz** [comment]
This seems like a bug with the classic editor, not with this plugin that just enables it. Lets handle it on the WordPress trac: https://core.trac.wordpress.org/ticket/46403
