### ISSUE TITLE
Strangly stop working

### ISSUE THREAD

**Issue by levskyA** [WordPress/classic-editor#99]
Hi
During development of the site  I encounter the issue if you try to create page it is only save in in  Draft mode  and if I wan to re-save page changes  "UPDATE button stop working, , so change do not get saved, however "Quick Edit" work fine.
I was looking in this issue and by unregistering plugins I discover that that file is get save fine if I go back to that new BLOCK SYSTEM that I really don like. So what I am wondering if any one ad similar issue and if it is how can we coarrect it I really don like using new sysytem.

Thank you in advance

**Comment by azaozz** [comment]
Sounds like some sort of error on the (old) Edit Post screen. Do you see any js errors in the browser tools? If yes, please look for a solution in the support forums, perhaps somebody already had a similar problem: https://wordpress.org/support/plugin/classic-editor/.

If not, perhaps try disabling plugins one by one until you find which causes it. In any case, better to post to the support forum for such errors. This plugin only enables access to the classic editor and the Edit Post screen, it doesn't changes how they work.
